### PR TITLE
un-relativize paths on the way out of Backend

### LINKED ISSUE #808: unexpected error: Invalid file from SlamEngine
When evaluating this query in the online demo environment:

```
select distinct count(*) as count, type, country from "/slamengine-test-01/olympics" WHERE UPPER(sport) = UPPER(:sport) GROUP BY country, type order by count desc
```

One gets the error: "Invalid file from SlamEngine", which is not only incorrect (the file exists), but is also a new regression due to recent updates (presumably in SlamEngine).

### PR DESCRIPTION
**Pull request by mossprescott**
Fixes #808.

### CODE REVIEW

File: web/src/test/scala/slamdata/engine/api/fs.scala [hunk 1]
```diff
@@ -1048,9 +1048,15 @@ class ApiSpecs extends Specification with DisjunctionMatchers with PendingWithAc
         withServer(backends1, config1) {
           val req = (root / "foo" / "").POST.setBody("select * from bar").setHeader("Destination", "/foo/tmp/gen0")
 
-          val result = Http(req > code)
+          val meta = Http(req)
+          val resp = meta()
 
-          result() must_== 200
+          resp.getStatusCode must_== 200
+          (for {
```
Comment (jdegoes) [inline web/src/test/scala/slamdata/engine/api/fs.scala]: Yay, a test that actually tests something!. :smile:

Comment (mossprescott) [inline web/src/test/scala/slamdata/engine/api/fs.scala]: Uh huh. Dispatch seems to want to go with the "one assertion per test" philosophy, but I really don't think that works well for API testing, or at least for these API tests.

But it turns out you can ignore that and just inspect the response, which is what I've started to do more.
