### PR TITLE
handle java.util.UUID when converting back from BSON (Fixes #624)

### LINKED ISSUE #624: admin: loading message appears forever in collection with 500 records
See [here](https://slamdata.supportbee.com/tickets/3878583) for context.

It looks like the table component may not be capable of displaying certain kinds of data (maybe it crashes, because it displays the Loading message forever). Or it could be an issue with the API.

The sample data suggests this could be connected to binary data, or arrays of binary data, which are probably not all that well tested.

### PR DESCRIPTION
**Pull request by mossprescott**
This is the Java representation for BinData(3, ...).

Also, give a slightly more comprehensible error when a value is not matched.

### CODE REVIEW

**Comment by mossprescott** [comment]
This is just the fix with no automated test, because we currently have no way of creating this kind of data. I don't think we want to support BinData sub-types in our JSON format, so we would need a MongoDB-specific test to cover this.

File: core/src/main/scala/slamdata/engine/physical/mongodb/bson.scala [hunk 1]
```diff
@@ -43,10 +43,18 @@ object Bson {
...
+        val dos = new java.io.DataOutputStream(bos)
+        dos.writeLong(x.getLeastSignificantBits)
+        dos.writeLong(x.getMostSignificantBits)
+        Binary(bos.toByteArray.reverse)
 
       // NB: the remaining types are not easily translated back to Bson,
       // and we don't expect them to appear anyway.
       // JavaScript/JavaScriptScope: would require parsing a string to our Js type
+
+      case _ => sys.error("unrecognized BSON value: " + v + " (" + v.getClass.getName + ")")
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/bson.scala]: Shouldn’t this function really be `Error \/ Bson`? `AnyRef` is not something it’s reasonable to cover all cases for.

Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/bson.scala]: Yes, that's conclusion I came to also, although in an ideal world we would know the behavior of the driver well enough to be certain that we had covered every case.

I did make the switch in this PR just because @jdegoes wanted to get a build out in a hurry and so I didn't want to pull that thread.

Comment (jdegoes) [inline core/src/main/scala/slamdata/engine/physical/mongodb/bson.scala]: Pretty please no more `sys.error` in the code. :smile: We can ship this but I'd prefer you just return a string, something like, "[Unknown data]", and then work on a real fix.

Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/bson.scala]: Yes, couldn't agree more. In my defense, this is just replacing an (invisible) `MatchError`, which is just as bad but produces a less helpful error and hides the problem. I'm writing a ticket to use `Error \/ Bson`, as @sellout requested.

In the meantime I'll replace the error with a bogus value. Coming up shortly.

Jeez!
