### PR TITLE
Fix some `fs.move` cases.

### LINKED ISSUE #693: Move/Rename
* When I try to move file to its own location (i.e. `bar/foo.json` -> `bar/foo.json`) it disappears with error 
```json
{ 
"serverUsed" : "localhost:27017" , 
"ok" : 0.0 , "errmsg" : 
"BadValue from namespace doesn't exist"
}
```
I remember that I had similar bug when I had tried to move directory to file path. (`/bar/foo/` -> `/bar/baz`) but can't reproduce it 
* When I move file to destination where other file exists, second file silently removed. Is it possible to add server-side check or additional parameter?

### PR DESCRIPTION
**Pull request by sellout**
Fixes #693.

* If src and dst are the same, it’s a NOP;
* if dst exists (and isn’t the same as src), fail; and
* modify regression tests so they don’t all try to write to the same
  output collection (since it would now require adding a deletion step).

### CODE REVIEW

File: it/src/test/scala/slamdata/engine/regression.scala [hunk 1]
```diff
@@ -60,7 +60,7 @@ class RegressionSpec extends BackendTest {
           t    <- backend.run {
                     QueryRequest(
                       query     = Query(query),
-                      out       = Some(tmpDir ++ Path("out")),
+                      out       = Some(tmpDir ++ Path("out") ++ genTempDir(fs).run),
```
Comment (mossprescott) [inline it/src/test/scala/slamdata/engine/regression.scala]: Should probably be just `Some(tmpDir ++ genTempFile(fs).run)`, unless we feel strongly about having "out" in the names, and in that case you should probably still use getTempFile.

Should be mapping over the Task from getTempFile? How pure are we attempting to be here?

Comment (sellout) [inline it/src/test/scala/slamdata/engine/regression.scala]: I considered mapping over the task, but then I saw that `tmpDir` already did `run`, so figure we were in the wild west of test code 😉 Doesn’t seem too complicated to hold on to `Task` a bit longer, though.

I’ll make the change to remove `out`.

Comment (jdegoes) [inline it/src/test/scala/slamdata/engine/regression.scala]: > Should be mapping over the Task from getTempFile? How pure are we attempting to be here?

Every day more pure than the day before. :smiling_imp:  No reason why these tests can't be 100% pure at some point.
