### PR TITLE
eradicate dangling references

### LINKED ISSUE #651: mongodb: order by with JS expression does not work when filtering is present
The following query produces an unsorted result:
```sql
select city, pop from zips where pop > 1000 order by length(city)
```

Looking at the physical plan, the sort key is not getting rewritten properly:
```
Chain
├─ $Read(zips)
├─ $Match
│  ╰─ Selector(Doc)
│     ╰─ Selector(BsonField.Name("pop") -> Gt(Int64(1000)))
├─ $SimpleMap
│  ├─ Expr({
│  │       "__tmp1": { "city": _.city, "pop": _.pop, "__tmp0": _.city.length },
│  │       "__tmp2": _
│  │     })
│  ╰─ Scope(Map())
├─ $Sort
│  ╰─ SortKey(__tmp0 -> Ascending)
╰─ $Project
   ├─ Name(city -> $__tmp1.city)
   ├─ Name(pop -> $__tmp1.pop)
   ╰─ ExcludeId
```

### PR DESCRIPTION
**Pull request by mossprescott**
There were a handful of situations where values were lost along the way 
as queries were planned, generating dangling references in the final plan.
The property-based planner tests now detect this error for all the queries we 
generate, and we now generate queries with sorting.

Specifically (and there are new regression tests for each of these):

1. Sorting by a JS expression with filtering present (fixes #651)
2. Implicit grouping, with only reduced projections, with filtering by JS
3. Explicit grouping, with only reduced projections, and filtering present

Along the way, a bunch of things got improved:

Fixed `ExprOp.toJs` to *not* translate `Include`; there's not enough information 
in the op, so it needs special handling by the caller.

`optimize` now removes unused fields in `SimpleMap`, when the expression is
a possibly nested `Obj`. Note: it works only if the JsMacro does not inspect 
the argument (which is essentially always the case).

Broke out the three parallel cases in `toCollectionBuilder` for 
`ShapePreservingBuilder` as functions, making the parallels more visible.
This is where most of the missing rewriting was added. Also added a missing 
prefix in the `ExprBuilder`.

`shift` now returns the new base, which is used in one of the cases for SPB.

Fixed the threading of state in `distinctBy` so it uses a consistent set of temp
names, and refactored it into a single `for` comprehension to preserve my sanity.

Deleted the special-case for `ShapePreservingF` in `Workflow.merge` which had the
hack to discard the result and therefore had no valid base on one side. This removes
one dependency on `merge` behavior. This change (along with the above) fixed the 
bug, but also resulted in a fair amount of silly nesting (projects where one or more 
fields are nested under a tmp, with no other fields at the root). This nesting could 
be removed by more intelligent optimization, or maybe by more intelligent combination
of projections.

Note: the other change to some plans is new `$project` ops following `SimpleMap`s to
flatten out the newly-nested shapes. It would be good to inline these in `coalesce`, but that 
doesn't work in general because we sometimes need a project in that position to flatten
the implied `value` field, and there's no way to tell if that's the case by looking only 
at the ``$project` and its source.

Oh, and I added some files to .gitignore.

### CODE REVIEW

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala [hunk 1]
```diff
@@ -1152,6 +1156,46 @@ object Workflow {
...
+      def loop(x: Term[JsCore]): Option[List[BsonField]] = x.unFix match {
+        case JsCore.Obj(values) => Some(values.toList.flatMap { case (k, v) =>
+          val n = BsonField.Name(k)
+          loop(v).map(_.map(n \ _)).getOrElse(List(n))
+        })
+        case _ => None
+      }
+      // Note: this is not safe if `expr` inspects the argument to decide what
+      // JS to construct, but all we need here is names of fields that we may
+      // be able to optimize away.
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala]: Is this unsafe-ness eliminated with the changes you’re currently working on? If not, I’d like this to be a FIXME with a ticket, so it gets a bit more attention.

File: core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala [hunk 2]
```diff
@@ -63,6 +63,16 @@ class PlannerSpec extends Specification with ScalaCheck with CompilerHelpers wit
...
   def beWorkflow(wf: Workflow) = beRight(equalToWorkflow(wf))
 
+
+  implicit def toBsonField(name: String) = BsonField.Name(name)
+  implicit def toLeftShape(exprOp: ExprOp): ExprOp \/ Reshape = -\/ (exprOp)
+  implicit def toRightShape(shape: Reshape): ExprOp \/ Reshape = \/-(shape)
+  def reshape(shape: (String, ExprOp \/ Reshape)*) =
+    Reshape(ListMap(shape.map { case (k, v) => BsonField.Name(k) -> v}: _*))
+  def grouped(shape: (String, GroupOp)*) =
+    Grouped(ListMap(shape.map { case (k, v) => BsonField.Name(k) -> v}: _*))
```
Comment (sellout) [inline core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala]: I want `Reshape` and `Grouped` to just be type aliases for the appropriate `ListMap`, but this wrapper to get rid of the noise is fine for now.

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala (hunk 1 above)
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala]: Yes, `expr` is no longer JsMacro in my wip/634 branch. I'll have to reimplement this when I merge it. Happy to add the ticket number here if you don't trust me.
