### PR TITLE
reduce the MongoDB driver's serverSelectionTimeout to 5 seconds

### LINKED ISSUE #877: It takes 30s for a bad mount configuration to be rejected
As of #863 / #870, the backend now verifies that it can connect to a mount before saving it; this is useful to the frontend, since it can now present feedback to the user and avoid entering an inconsistent state.

However, if an incorrect mount is provided (e.g. with the wrong port), it takes 30 seconds for it to be rejected. On the frontend, this translates to the user waiting for 30 seconds before they receive the following feedback: 

```
{"error":"Invalid server and / or port specified.","errorDetail":"Timed out after 30000 ms while waiting for a server that matches PrimaryServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=ds045089.mongolab.com:45087, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]"}
```

It this something that can be improved? Ideally it would fail a lot sooner, but if that's not possible, we should probably open a ticket on the frontend to show some indication to the user that we are validating the mount (since it just looks like the app got wedged).

### PR DESCRIPTION
**Pull request by mossprescott**
Fixes #877.

### CODE REVIEW

File: core/src/main/scala/slamdata/engine/physical/mongodb/util.scala [hunk 1]
```diff
@@ -26,9 +26,13 @@ import scalaz.Memo
 import com.mongodb._
 
 object util {
+  private val DefaultOptions =
```
Comment (jdegoes) [inline core/src/main/scala/slamdata/engine/physical/mongodb/util.scala]: This should be inlined (placed into the code block) because it may be mutated by MongoDB.

Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/util.scala]: Ah, the _builder_ is mutable, yes. OK will do.
