### PR TITLE
Disable array_concat.

### LINKED ISSUE #597: Error when ORDER BY references raw field name when SELECT aliases the field, and field is in GROUP BY and additional fields are returned in the SELECT results
This had worked against the admin jar released under SHA d9c9ac0 (SNAPHSHOT 861) and fails under SHA 4a9b703 (SNAPHSHOT 869).  There is an easy workaround of changing the ORDER BY clause to reference the field Alias name, versus the raw field name.  However, I believe ANSI SQL allows for referencing the actual field names in the ORDER BY, and this appears to be a regression issue.
```
SELECT distinct category AS "Result Alias", COUNT(*)
	FROM "/SimpleParent"
	GROUP BY category
	ORDER BY category
```
Fails with:
```
java.lang.RuntimeException: cannot merge class slamdata.engine.physical.mongodb.Workflow$$Read with class slamdata.engine.physical.mongodb.Workflow$$Group
```
But any of the following mitigate the error (the first two at least still provide access to the same result data):
* Changing the ORDER BY to be ORDER BY "Result Alias"
* Removing the AS "Result Alias" from the SELECT
* Removing the ORDER BY clause
* Removing the GROUP BY clause
* Removing the COUNT(*) from the SELECT results

### PR DESCRIPTION
**Pull request by sellout**
Fixes #597.

It was breaking queries that threw away the resulting aray, and it
doesn’t work in practice anyway, so it is cauterized to avoid the damage
until we get it working.

Added three integration tests – one that this change fixes, and two more
that were already broken, but at least now are tracked by pending
tests (and #600).

### CODE REVIEW

File: core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala [hunk 1]
```diff
@@ -592,7 +592,9 @@ object MongoDbPlanner extends Planner[Workflow] with Conversions {
         case `ObjectConcat` =>
           Arity2(HasWorkflow, HasWorkflow).flatMap((objectConcat(_, _)).tupled)
         case `ArrayConcat` =>
-          Arity2(HasWorkflow, HasWorkflow).flatMap((arrayConcat(_, _)).tupled)
+          // FIXME: the implementation is wrong. (#600)
+          fail(InternalError("array_concat is not currently implemented."))
```
Comment (jdegoes) [inline core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala]: This can't make any queries work now which didn't work before -- right? So how does it help solve the error our user is encountering?

Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala]: It does. The root problem is that `Workflow.merge` doesn’t `fail`, it `error`s. Which makes me realize (thank you) that the better solution is to make `Workflow.merge` use our `StateT[\/]` stack instead of just `State`.

So … nobody merge this. Better version coming!

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala [hunk 2]
```diff
@@ -845,74 +869,23 @@ object WorkflowBuilder {
...
-              case (item, index) =>
-                (BsonField.Index(index) -> -\/(Literal(item)))
-            } ++ reshape): _*)))),
-          DocVar.ROOT(),
-          SchemaChange.MakeArray(seq.zipWithIndex.map {
-            case (item, index) =>
-              // TODO: make the schema for the values more specific (#437)
-              (index -> SchemaChange.Init)
-          }.toListMap ++ array)))
+      case (ValueBuilderF(Bson.Arr(seq)), ArrayBuilderF(src, shape)) =>
```
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: Don't we need a case with the arguments reversed?

Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: Whoops – yes! Although we can’t explicitly test any of it until we fix some other array-related stuff.

And after this merge, I’d like to pull your `combine` stuff out of `objectConcat`, since it’ll be useful for `arrayConcat` as well.

**Comment by mossprescott** [comment]
No other comments. Looks good.

**Comment by mossprescott** [comment]
And thanks for merging the conflicts in objectConcat :)
