### PR TITLE
delete Workflow.merge (fixes #634)

### LINKED ISSUE #634: refactor: delete Workflow.merge
`Workflow.merge` is messy, frequently incorrect, and just a bad idea. It’s only called in one place now, and that can be replaced with something much more specific.

It’s call site is `WorkflowBuilder.toCollectionBuilder(ShapePreservingBuilder)` and it’s used to try to push a ShapePreservingOp (match, limit, skip, sort) earlier in the workflow. Ideally, this would be handled by a `Workflow` optimization that just ensured that all the required fields for the op existed (with possible rewriting of the op). Then we could do the merge in `WorkflowBuilder` and let this optimization pass handle this later. That would eliminate a bunch of special casing in `WorkflowBuilder.toCollectionBuilder(ShapePreservingBuilder)` along the way and probably improve a wider range of queries.

In the interim, `Workflow.merge` could be cleaned up (disjunction instead of `sys.error`) and narrowed to focus on this one task (rather than attempting to merge arbitrary workflows). EG, when we call `Workflow.merge(src, chain(inputs, shapePreservingOp))` we know that we don’t need to preserve the fields on the right beyond the insertion of `shapePreservingOp`.

### PR DESCRIPTION
**Pull request by mossprescott**
Instead, re-write the complete workflow after it's generated,
re-ordering shape-preserving ops to push match/skip/limit as
early as possible, while keeping sort as late as possible.

SpliceBuilders are now "materialized" to JS earlier,
so that their results can be projected under a temp name,
and properly combined with other results.

JsCore changes:

1. `JsFn`, an alternative to JsMacro which allows for inspection of
the partially-constructed Js.
2. `JsCore.Let` now binds exactly one name.

### CODE REVIEW

**Comment by mossprescott** [comment]
Comments requested especially on `JsFn`, which is not only a dumb name, but also a dumb idea more generally. It might be better to to port `bound` or come up with some equivalent, but I could not figure out how to get that approach to work. As is, JsFn's `base` is a pain: it's hard to read in test output, it requires a manual scope-sensitive `substitute` function, and it just adds one more name to worry about that isn't really ever used.

**Comment by mossprescott** [comment]
Rounds to 80%!

**Comment by sellout** [comment]
The JsFn analysis could be accomplished by applying the JsMacro (which is kind of like Pseudo-HOAS) and inspecting the result, right? Or is there a more fundamental difference than the JsFn just having a more direct representation? If it’s the former, I assume you think the JsFn approach is at least superior to the `JsCore => JsCore` approach.

Bound may be better, but worrying about that for a very standalone thing like JsFn/Macro is probably overkill. Getting to the point where we could use it for JsCore itself (as well as LogicalPlan, and possibly the SQL AST) would be great, though (but then we have to deal with more complicated folds, so …).

File: core/src/main/scala/slamdata/engine/javascript/jscore.scala [hunk 1]
```diff
@@ -69,7 +69,7 @@ object JsCore {
   // ListMap here lets us be explicit about what result we'd like to see.
   case class Obj[A](values: ListMap[String, A]) extends JsCore[A]
 
-  case class Let[A](bindings: Map[String, A], expr: A) extends JsCore[A]
+  case class Let[A](name: Ident, expr: A, body: A) extends JsCore[A]
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: I think this change makes sense. JS doesn’t have parallel binding, right? I think there are various extensions for that, but nothing available through MongoDB at least.

File: core/src/main/scala/slamdata/engine/javascript/jscore.scala [hunk 2]
```diff
@@ -94,8 +94,9 @@ object JsCore {
     case Obj(values)         =>
       Js.AnonObjDecl(values.toList.map { case (k, v) => k -> toUnsafeJs(v) })
 
-    case Let(bindings, expr) =>
-      Js.Let(bindings.mapValues(toUnsafeJs(_)), Nil, toUnsafeJs(expr))
+    // TODO: collapse nested lets
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: Oh right, so the way we do `Let`s (and parallel binding) in JS is anonymous functions. I would suggest that we either have both `Js` and `JsCore` have multi-binding `Let`, or neither. Converting multi-binding `Let` into something other than an anonymous function in JS is a bit more complicated, but I also don’t think it’s all that fundamental, so it can be tossed.

File: core/src/main/scala/slamdata/engine/javascript/jscore.scala [hunk 3]
```diff
@@ -226,8 +227,9 @@ object JsCore {
       case Obj(values)         =>
         Js.AnonObjDecl(values.toList.map { case (k, v) => k -> v.toJs })
 
-      case Let(bindings, expr) =>
-        Js.Let(bindings.mapValues(_.toJs), Nil, expr.toJs)
+      // TODO: collapse nested Lets
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: Same.

File: core/src/main/scala/slamdata/engine/javascript/jscore.scala [hunk 4]
```diff
@@ -303,3 +332,31 @@ object JsMacro {
...
+  def apply(x: Term[JsCore]) = expr.substitute(base.fix, x)
+
+  def const(x: Term[JsCore]) = JsFn(JsCore.Ident("__unused"), x)
+
+  def >>>(that: JsFn): JsFn =
+    if (this == JsFn.identity) that
+    else if (that == JsFn.identity) this
+    else JsFn(this.base, JsCore.Let(that.base, this.expr, that.expr).fix)
+
+  def toMacro = JsMacro(apply)
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: So, there’s still JsMacro … do we need it for something in particular, or does it just complicate these changes too much to do it in the same PR? If it’s the latter, we need a ticket for removing it later.

Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: I can't find an example of a case where we use the full power of `JsMacro` (that is, where we actually inspect the argument and do something other then simply inserting it into a fixed template), but without attempting the conversion it's hard to say for sure. In any case, I think we could handle any such cases by deferring the work to "simplify".

I mainly didn't switch over because I'm not that happy with how `JsFn` works at present. I could use your help figuring out what variant of *bound*, *Abstract Binding Trees*, or what-have-you is what we really want.

File: core/src/main/scala/slamdata/engine/javascript/jscore.scala (hunk 2 above)
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: `Js.Let` is just a heklper function and not an actual node because there is no such construct in JavaScript. However, EcmaScript 6 does define a `let` statement, so we felt it might make some amount of sense to define it there, even if we currently render only to a let-less JavaScript syntax.

I just looked a little closer and it turns out:

1. ES6's `let` statement actually does allow multiple bindings.
2. It has virtually nothing else in common with our "functional" `Let`.

Therefore I think it makes sense to keep it as helper function only, and really the only problem with it is that it's called `Let`, which is confusing. Maybe it should be called "IIFE"? Since JS functions can take multiple parameters, I so no reason not to expose that directly.

Comment (sellout) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: I feel like “let” is a pretty clear concept, so # 2 on that list terrifies me a little. I hesitate to call it IIFE only because I hope we eventually convert a single-binding let into a variable declaration. (Or should we have a different helper for that?)

Anyway, I’m mostly nervous here about wanting to convert nested lets into parallel ones. It’s tricky, because of `Let(x, a, Let(y, expr(containing(x)), …))`.

File: core/src/main/scala/slamdata/engine/physical/mongodb/package.scala [hunk 5]
```diff
@@ -18,4 +20,5 @@ package object mongodb {
 
   // TODO: parameterize over label (#510)
   def freshName: State[NameGen, BsonField.Name] =
-    freshId("tmp").map(BsonField.Name(_))}
+    freshId("tmp").map(BsonField.Name.apply)
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/package.scala]: So, I’ve seen a couple changes from `(_)` to `.apply` and `(_, _)` to `.apply _`. Is this really a win?

Granted, anything other than `.map(BsonField.Name)` is 😞, but is `(_)` not resolved at compile time?

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala [hunk 6]
```diff
@@ -132,7 +132,7 @@ object Workflow {
   def task(op: Workflow): WorkflowTask =
     (WorkflowTask.finish _).tupled(finalize(op).para(crush))._2
 
-  def finish(op: Workflow): Workflow = deleteUnusedFields(op, None)
+  val finish: Workflow => Workflow = reorderOps _  >>> deleteUnusedFields _
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala]: If I squint, this looks like it could be a zygohistomorphic prepromorphism (splitting `deleteUnusedFields` into `findUnusedFieldsƒ` and `deleteFieldsƒ`), but

1. I’m probably wrong and
2. I’m too tired to try to figure it out.

So everyone wins 😉

File: core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala [hunk 7]
```diff
@@ -1217,19 +1231,14 @@ class PlannerSpec extends Specification with ScalaCheck with CompilerHelpers wit
...
-                  "city" -> DocField("city"),
-                  "pop" -> DocField("pop"))),
-              ExcludeId),
-            $limit(5),
-            $project(
-              reshape(
-                "city" -> DocField("__tmp0" \ "city"),
-                "pop" -> DocField("__tmp0" \ "pop")),
-                ExcludeId))
+            $limit(5))
```
Comment (sellout) [inline core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala]: Nice 👍

File: core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala [hunk 8]
```diff
@@ -1238,9 +1247,9 @@ class PlannerSpec extends Specification with ScalaCheck with CompilerHelpers wit
         beWorkflow {
           chain(
             $read(Collection("zips")),
+            $limit(5),
             $project(Reshape(ListMap(BsonField.Name("city") -> -\/ (DocField(BsonField.Name("city"))))),
-              IgnoreId),
-            $limit(5))
+              IgnoreId))
```
Comment (sellout) [inline core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala]: Also nice 👍

**Comment by sellout** [comment]
Well, this needs changes before I merge anyway, so that lets me sleep on the `JsFn` question, at least. Overall, I’m not too worried about it, because it’s nothing compared to the monstrosity that was `Workflow.merge`, plus the fact that getting rid of `Workflow.merge` actually improves some queries with shape preservers.

I don’t really like having _both_ JsFn and JsMacro around. As far as bound/abt/etc., we might just need to wait and corner @jonsterling at LambdaConf 😉

**Comment by mossprescott** [comment]
I'll have a go at converting everything to JsFn. Unless I run into a show-stopper, I think that will be better than having both around. We can always convert to the better thing when we figure it out.

File: core/src/main/scala/slamdata/engine/physical/mongodb/package.scala (hunk 5 above)
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/package.scala]: I haven't checked the generated bytecode to see if the compiler gets rid of it, but at some point it started to make more sense to me not to write it as if a new anonymous function was being defined when one already exists, so I started referring to the apply methods explicitly. But yeah, it's uglier.

Of course I'd like to write `.map(BsonField.Name)` and be done with it, but when that doesn't compile, then we have to choose.

Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/package.scala]: OK, two things:

`.map(BsonField.Name)` actually works in this case, so I'll use that.

It looks like there's not much difference between `(_)` and `.apply` in terms of what extra bytecode is generated, but either one is worse than using the naked constructor name:

source | generated
------ | ----------
`.map(BsonField.Name)` | no "anonfun" class
`(_)` |  1275 bytes
`.apply` | 1277 bytes
`(_ + "foo")` | 1476 bytes

I can't get javap to disassemble the generated class (which is called `slamdata/engine/physical/mongodb/package$$anonfun$freshName$1.class`), but I don't think there will be much to see there anyway. Not sure how much difference any of this makes, but it certainly doesn't seem like `.apply` is doing anything for the overhead.

Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/package.scala]: Any idea why `BsonField.Name` works, but some other constructors don’t? Or is this just another one of those things where I end up writing it the good way first, and then fixing it whenever the compiler complains.

On the one hand, I feel like I should make an effort to understand Scala better, but on the other, I feel like I’m not going to arrive at any reasonable set of principles I can apply 😕

Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/package.scala]: Nope, I'm applying exactly the same algorithm ;-)

I think it's worth understanding Scala's weird edge-cases only insofar as it helps to avoid them. If I figure this one out, I'll pass it along.

File: core/src/main/scala/slamdata/engine/javascript/jscore.scala (hunk 2 above)
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: Right, I wasn't thinking about that.

As far as I could tell, we don't actually produce any nested lets, so the issue doesn't currently arise. We can optimize it sometime in the future if we notice it happening. I guess I'll take out the TODOs.

So am I changing `Js.Let`?

**Comment by mossprescott** [comment]
Switching everything to `JsFn` didn't break anything or require any fundamental changes. I did have to add a coupe of cases to `simplify` to eliminate some new Lets coming from `JsFn.>>>`. Now I'm staring at a couple of WorkflowOp test failures where the result *looks* the same but somehow renders to different JavaScript. Grumble.

**Comment by mossprescott** [comment]
This is ready to go except for the question of `Js.Let`, collapsing nested `JsCore.Let`s (when possible), and the pair of TODOs referring thereto.

File: core/src/main/scala/slamdata/engine/javascript/jscore.scala (hunk 2 above)
Comment (sellout) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: Ah, thought I responded here, but apparently not.

I think just take out the TODOs.

**Comment by mossprescott** [comment]
Still not sure why this change seems to reduce coverage, except that there are a couple of cases in WorkflowBuilder.merge that I was not able to test (at least one because of a known bug in the type checker). In any case, I couldn't stomach dipping back below 80%, hence the otherwise unrelated added tests.

I still want to revisit JsFn, but this is an improvement over what we had.

Ready to merge.
