### PR TITLE
fix temporary collection leaks

### LINKED ISSUE #821: mongodb: temp collection left behind if destination path exists
If the client specifies a path for the result of a query (e.g. when using the POST /query API), and there is already a collection there, then a runtime error occurs and the temporary collection is left behind.

```
$ curl -i -X POST -d 'select pop from zips' -H "Destination: tmp000" http://localhost:8180/query/fs/local/test?limit=10
HTTP/1.1 200 OK
...
$ curl -i -X POST -d 'select pop from zips' -H "Destination: tmp000" http://localhost:8180/query/fs/local/test?limit=10
HTTP/1.1 500 Internal Server Error
...
{"error":"uncaught: com.mongodb.MongoCommandException: Command failed with error -1: 'target namespace exists' on server localhost:27017. The full response is { \"ok\" : 0.0, \"errmsg\" : \"target namespace exists\" }"}
```
After the second attempt, a collection named something like `tmp.gen_284215a4_0` is left behind, containing the result of the query.

### PR DESCRIPTION
**Pull request by mossprescott**
Fix a bug where, whenever a query was run without a specified output path, it
would actually be executed twice, and then only the second temporary result
would be deleted after the result was returned to the client. This meant that
GET queries were taking twice as long as they should, and were leaking one
copy of their results.

Fix another bug where a query would fail if the specified ouput collection
already existed, and leave behind the temporary result (which fixes #821).

Moved code to recursively list files from the web layer to `Backend.lsAll`.

Related fixes in the REPL:
- implement `env`
- fix parsing and handling of paths for the `[path] := select ...` command

### CODE REVIEW

**Comment by jdegoes** [comment]
:dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers:

File: core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala [hunk 1]
```diff
@@ -165,12 +169,14 @@ sealed trait MongoWrapper {
   def get(col: Collection): Task[MongoCollection[Document]] =
     Task.delay(db(col.databaseName).getCollection(col.collectionName))
 
-  def rename(src: Collection, dst: Collection): Task[Unit] =
+  def rename(src: Collection, dst: Collection, dropTarget: Boolean): Task[Unit] =
```
Comment (jdegoes) [inline core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala]: Let's introduce `RenameSemantics` like you did for `move`, to be consistent and avoid booleans.

File: core/src/main/scala/slamdata/engine/repl/repl.scala [hunk 2]
```diff
@@ -277,8 +279,16 @@ object Repl {
   def run(args: Array[String]): Process[Task, Unit] = {
     import Command._
 
-    def eval(s: RunState, t: PathTask[Unit]): Process[Task, Unit] =
-      Process.eval(t.run.flatMap(_.fold(err => s.printer("Path error: " + err.message), Task.now)))
+    def eval(s: RunState, t: PathTask[Unit]): Process[Task, Unit] = {
+      Process.eval(for {
+        v <- t.run.attempt
+        _ <- v.fold(
+          err => s.printer("Runtime error: " + err),
```
Comment (jdegoes) [inline core/src/main/scala/slamdata/engine/repl/repl.scala]: Should this be `err.message` like the below?

File: core/src/main/scala/slamdata/engine/repl/repl.scala [hunk 3]
```diff
@@ -277,8 +279,16 @@ object Repl {
...
+          _.fold(
```
Comment (jdegoes) [inline core/src/main/scala/slamdata/engine/repl/repl.scala]: Also this looks like a nested Either. If the error types align you can flatten using `join`, or whatever it's called in Scalaz.

File: core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala (hunk 1 above)
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala]: Sure. We'll eventually have `Append extends MoveSemantics` but not the equivalent for RenameSemantics, I think, so I won't use one type for both.

File: core/src/main/scala/slamdata/engine/repl/repl.scala (hunk 2 above)
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/repl/repl.scala]: This one is `Throwable` (from `Task.attempt`), so there's no `message` and `toString` seems like the way to go, although there is is also `getMessage()`. The other is `PathError`, so it has `message`, which is preferred.

File: core/src/main/scala/slamdata/engine/repl/repl.scala (hunk 3 above)
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/repl/repl.scala]: Yes, it's `Throwable \/ (PathError \/ Unit)`, and if I `join` them I end up with `Throwable \/ Unit`, and I can't use `message` or show "Runtime Error" vs. "Path Error".

As a more general thing, I'm *really* not a fan of the way this sort of thing reads: `v <- t.run.attempt`, where `run` is unwrapping the `Task[PathError \/ Unit]` inside the `EitherT` (`PathTask`) value, and then `attempt` is adding the other `\/`. I don't see any way around it, though, since `attempt` is a Task-specific thing. I guess mostly I just don't like seeing `run` show up in the code when we're *not* running the Task. Hmm.

I'm definitely open to suggestions about how to make this sort of thing read better, because I think it has more than esthetic consequences. See my next comment about the bug I found.

File: core/src/main/scala/slamdata/engine/backend.scala [hunk 4]
```diff
@@ -229,14 +239,13 @@ trait PlannerBackend[PhysicalPlan] extends Backend {
...
-            rez0    <- rez1
-            renamed <- (rez0, req.out) match {
+            rez    <- liftP(evaluator.execute(plan))
+            renamed <- (rez, req.out) match {
               case (ResultPath.Temp(path), Some(out)) => for {
-                _ <- move(path, out)
+                _ <- move(path, out, Overwrite)
               } yield ResultPath.User(out)
-              case _ => rez1
+              case _ => liftP(Task.now(rez))
```
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/backend.scala]: This is the subtle and horrible bug. `rez1` appeared twice on the right side of `<-`, but because it was only in some cases, and maybe because it was hidden in the "otherwise" case, it wasn't spotted.

But `<- rez1` here happens to be what causes the query plan to be executed (and temps to be generated), so that was really bad.

The fix counter-intuitively involves extra wrapping of the already-evaluated `rez` (which used to be called `rez0`).

This was introduced when we switched from `Task` to `PathTask`, and I've fixed at least a couple of other bugs like this where effects weren't being sequenced properly.

@sellout: I'm concerned that this means we're either asking for trouble with the way we're doing things, or we're just not reviewing these changes well enough, or maybe FP in general is just a bad idea. I'm pretty sure at least one of those is true anyway. Let's discuss this when you're back in town.

**Comment by mossprescott** [comment]
Updated.

File: core/src/main/scala/slamdata/engine/backend.scala (hunk 4 above)
Comment (jdegoes) [inline core/src/main/scala/slamdata/engine/backend.scala]: The above code is tangled and in need of simplification. But regardless, `rez1` is a computation described by the execution of the plan using the evaluator, so yeah, if you sequence it twice, its effects will be run twice, which is the correct and expected semantics — exactly equivalent to inserting the same statement (`runEvaluator()`) two times inside a code block.
