### PR TITLE
Unify fields that are flattened in both multiple contexts.

### LINKED ISSUE #384: missing case in `WorkflowBuilder.objectConcat`
```sql
select * from zips z1 join zips z2 on z1._id = z2._id join zips z3 on z2._id = z3._id
```
causes a `CannotObjectConcatExpr` error. Right now `objectConcat` explicitly handles a bunch of cases (but not all). Covering the rest would be good, somehow implementing it without SchemaChange² cases would be awesome.

### LINKED ISSUE #407: mongodb: merging of array flattens may not work correctly
See [this Stackoverflow question](http://stackoverflow.com/questions/26520379/mongodb-aggregate-sort-by-match/26536344#26536344) for context.

In the graph, if two nodes perform a dimensional expansion or contraction, they must be merged at the same level, to avoid repeating the dimensional transformation.

### LINKED ISSUE #524: mongodb: bad plan with Group, Filter, and complex projections
With certain complex queries, the planner fails to merge workflows properly and ends up replicating the $match op multiple times, with broken references.

For example (surely not the simplest example) this query ends up with the $match replicated 4 times:
```sql
select lower(min(lower(city))) as p0, lower(city) as p1, (min(length(city))) / (1000) as p2, lower(city) as p3 from zips where ((pop) - (1)) < (100) group by city, pop
```

That example, and any number of others, are easily generated by enabling the pending planner test marked with this issue number.

Note: many similar cases are fixed in #469, and this will all be affected by work going on for #407.

### PR DESCRIPTION
**Pull request by sellout**
Fixes #407.

This replaces the `ShapePreservingBuilder` with a new one that postpones
merging the incoming builders and adds a new `FlatteningBuilder` to
handle both the `$unwind` of `flattenArray` and the `$flatMap` of
`flattenObject` consistently and without throwing away the history of
builders.

The new `ShapePreservingBuilder` allows us to get rid of the complicated
`These` (`\&/`) contents of GroupBuilder, since we no longer have groups
that already have a document and are also having a new field built on
them. This also gets rid of a few bad/impossible states for a
GroupBuilder.

A lot of operations just “pass through” the new
`ShapePreservingBuilder`, being applied to the `src` builder, then
having the SPB wrapped around the result of that.

A few other issues were also fixed here:

* cover more cases in `merge`, `objectConcat`, and `distinctBy` (fixes #384),
* catch a bug where we weren’t rewriting a DocVar (fixes #524),
* implement delegate for `WorkflowBuilder.merge`, and
* statically check if we can `projectField` from a `GroupBuilder`.

One negative side effect is that #503 rears its head a bit more, as we
now manage to build a better `DocBuilder` rather than ending up with a
`$simpleMap` that we later tack a `$project` onto. This affects
`selectArrayElement.test`.

### CODE REVIEW

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala [hunk 1]
```diff
@@ -12,7 +12,6 @@ import slamdata.engine.javascript._
 
 import scalaz._
 import Scalaz._
-import \&/._
```
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: :+1:

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala [hunk 2]
```diff
@@ -103,6 +110,23 @@ object WorkflowBuilder {
...
+  case object Array extends StructureType
+  case object Object extends StructureType
+
+  case class FlatteningBuilderF[A](src: A, typ: StructureType, field: DocVar)
+      extends WorkflowBuilderF[A]
+  object FlatteningBuilder {
+    def apply(src: WorkflowBuilder, typ: StructureType, field: DocVar) = {
+      src.unFix match {
+        case FlatteningBuilderF(_, _, _) =>
+          sys.error("nooooooo!")
```
Comment (jdegoes) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: Exactly my reaction on seeing `sys.error`!!! :smile: Maybe generalize the type of apply so it can error if necessary?

Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: Cute, but wouldn't we rather have this in a `-\/`? As a rule, how does one do partial constructors if one doesn't want to use exceptions? I suppose the type could be `\/` here, but that's only because we happen to be wrapping in `Term` anyway.

@jdegoes?

File: it/src/test/resources/tests/selectArrayElement.test [hunk 3]
```diff
@@ -3,14 +3,14 @@
...
-                 {"city": "CUSHMAN", "1": -72.51565},
-                 {"city": "BARRE", "1": -72.108354},
-                 {"city": "BELCHERTOWN", "1": -72.410953},
-                 {"city": "BLANDFORD", "1": -72.936114},
-                 {"city": "BRIMFIELD", "1": -72.188455},
-                 {"city": "CHESTER", "1": -72.988761},
-                 {"city": "CHESTERFIELD", "1": -72.833309},
-                 {"city": "CHICOPEE", "1": -72.607962},
-                 {"city": "CHICOPEE", "1": -72.576142}]
+    "expected": [{"value": {"city": "AGAWAM", "1": -72.622739}},
```
Comment (jdegoes) [inline it/src/test/resources/tests/selectArrayElement.test]: This looks like a regression to me.

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala [hunk 4]
```diff
@@ -84,16 +91,16 @@ object WorkflowBuilder {
       Term[WorkflowBuilderF](new DocBuilderF(src, shape))
   }
 
+  type Contents[A] = A \/ ListMap[BsonField.Name, A]
   type GroupValue = ExprOp \/ GroupOp
-  type GroupContents = GroupValue \&/ ListMap[BsonField.Name, GroupValue]
+  type GroupContents = Contents[GroupValue]
```
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: OK, so I'm happy about getting rid of `\&/`, but nested `\/` always hurts my eyes. Can we make one of these types a trait that says what it means?

Maybe `sealed trait Contents[A]` with `Contents.Expr` and `Contents.Doc`. Or on the other hand maybe it's time to make `GroupValue` an ADT, with `GroupValue.Pushed` and `GroupValue.Reduced`.

File: it/src/test/resources/tests/unifyFlattenedFieldsWithUnflattened.test [hunk 5]
```diff
@@ -0,0 +1,16 @@
+{
+    "name": "unify flattened fields with unflattened field",
+    "data": "zips.data",
+    "query": "select _id as zip, loc[*] from zips order by loc[*] limit 10",
```
Comment (jdegoes) [inline it/src/test/resources/tests/unifyFlattenedFieldsWithUnflattened.test]: I assume the ordering is intended to prove there are no duplicates, as would be expected from doubly-unwinding???

File: it/src/test/resources/tests/selectArrayElement.test (hunk 3 above)
Comment (mossprescott) [inline it/src/test/resources/tests/selectArrayElement.test]: Yes, I believe he mentioned it in the PR.

File: core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala [hunk 6]
```diff
@@ -1673,7 +1690,7 @@ class PlannerSpec extends Specification with ScalaCheck with CompilerHelpers wit
         maxUnwindOps(wf, 1)
         maxMatchOps(wf, 1)
       }
-    }.set(maxSize = 20, minTestsOk = 300).pendingUntilFixed("#524")
+    }.set(maxSize = 20, minTestsOk = 300)
```
Comment (mossprescott) [inline core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala]: :+2:

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala (hunk 2 above)
Comment (jdegoes) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: Make the constructor private, e.g.:

```scala
case class FlatteningBuilderF private [A](src: A, typ: StructureType, field: DocVar)
```

Then define the apply method to return `\/`.

Actually, it occurs to me the above code is probably not trying to be a "smart constructor" because it returns a `Term` and not a `FlatteningBuilderF`, so it should probably be renamed, and of course it's return type can easily be changed to `\/`.

Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: Sorry guys – this is simply debugging stuff that should have been removed. I just wanted to see exactly where (from the stack) a particular set of builders was being put together.

File: it/src/test/resources/tests/selectArrayElement.test (hunk 3 above)
Comment (sellout) [inline it/src/test/resources/tests/selectArrayElement.test]: Indeed – this is actually the result of an improvement to the code, but it means an existing issue (#503) pops up more often.

File: it/src/test/resources/tests/unifyFlattenedFieldsWithUnflattened.test (hunk 5 above)
Comment (sellout) [inline it/src/test/resources/tests/unifyFlattenedFieldsWithUnflattened.test]: Heh, that would have been good – but no. This same test is in PlannerSpec, so we check there’s only a single unwind there. This just uses ordering because the other new test uses filtering and might as well cover the various places we can run into the repeated flattening.

Comment (jdegoes) [inline it/src/test/resources/tests/unifyFlattenedFieldsWithUnflattened.test]: On the same note, is a *single* regression test sufficient to fully exercise all this new code? Seems like the answer would be no.

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala (hunk 4 above)
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: I agree, one of these should change. I’ll have to think about it a bit.

File: it/src/test/resources/tests/unifyFlattenedFieldsWithUnflattened.test (hunk 5 above)
Comment (sellout) [inline it/src/test/resources/tests/unifyFlattenedFieldsWithUnflattened.test]: Hey, I added _two_, along with two planner tests! A lot of this is refactoring of existing stuff, so existing tests test much of it. The coverage did increase by 0.11% (despite what stupid Coveralls wants you to believe), but I can check the coverage and see what paths are missing (really wish I could overlay coverage on a diff).

**Comment by sellout** [comment]
to do list:
- [x] remove debugging code
- [ ] change `Contents` from a type alias to a sum of `Expr` and `Doc`
- [ ] add tests to improve coverage

File: core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala [hunk 7]
```diff
@@ -570,12 +563,12 @@ class PlannerSpec extends Specification with ScalaCheck with CompilerHelpers wit
       plan("select bar from foo order by bar") must
         beWorkflow(chain(
           $read(Collection("foo")),
+          $sort(NonEmptyList(BsonField.Name("bar") -> Ascending)),
```
Comment (mossprescott) [inline core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala]: This seems like a minor regression to me. I think we had said projects should precede other ops to reduce the data size as early as possible. Not that I think we were trying particularly hard. Is this just a side-effect?

**Comment by mossprescott** [comment]
I see no other problems.

File: core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala (hunk 7 above)
Comment (sellout) [inline core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala]: This is the result of my hack in `toCollectionBuilder(ShapePreservingBuilder)` to pull ops up the chain when possible, because for `$match`, `$limit`, and `$skip`, we want them at the beginning (to take advantage of indexes and to reduce the number of records we have to process). I did consider only apply this when the op isn’t `$sort`, but it turns out to be a little more complicated. Logically, it fits between `$match` and `$limit`, but if we insert a `$project` in between `$match` and `$sort`, then we 1) can’t easily turn the whole thing into a `$mapReduce`, 2) end up executing the projection on every record, even if there is a `$limit(10)` after it, and 3) possibly need a second projection to clean up the sort keys afterward.

So, the waters seemed muddy enough that I didn’t want to add a special case for something that may actually pessimize the query. I think it’s a performance point we should look into, but (at least to me) the best ordering isn’t clear.

It is a simple enough change, though, so if it’s clear to you or John, I can conditionalize it on not-`$sort`.

Comment (slamdata-build) [inline core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala]: I don't have an answer to all that, and I don't think it's a pressing
issue, so I say leave it and I'm sure we'll be looking into this sort of
thing more deeply in the future anyway. By then we'll have a better
representation to analyze/optimize, too.
