### PR TITLE
consume first chunk of scan, handle errors, then stream the rest

### LINKED ISSUE #782: API: entire result brought into memory when it should be streamed
This means we would run out of memory and fail to respond if a client tries to stream a very large result (larger than will fit in the heap in the form of `Data` values).

See https://github.com/slamdata/slamengine/commit/56ce4ac81a77c16e17a4ffcd5b9723c9c1a7b676#diff-b37ea18e5f5bbd36b3bb04e6f178f4e7R81.

The difficulty is how to handle failure. Currently, failures resulting from problems with the request are returned in `Process[PathTask, Data]`, so you have to consume the entire process to know if anything went wrong.

### PR DESCRIPTION
**Pull request by mossprescott**
Fixes #782.

Includes an ugly back-port of `unconsOption` from scalaz-stream/master.

### CODE REVIEW

File: web/src/main/scala/slamdata/engine/api/fs.scala [hunk 1]
```diff
@@ -77,34 +77,51 @@ final case class FileSystemApi(backend: Backend, contentPath: String, config: Co
...
+    val v1: Process[Task, Throwable \/ String] = v.translate(unstack).attempt()
+    v1.unconsOption.flatMap(_ match {
+      case Some((first, rest)) =>
+        first.fold(
+          {
+            case e: PathError => handlePathError(e)
+            case e: ScanError => handleScanError(e)
+            case err => InternalServerError(err.toString)
+          },
+          _ => Ok((Process.emit(first) ++ rest).map(_.fold("error: " + _, ɩ))))
```
Comment (sellout) [inline web/src/main/scala/slamdata/engine/api/fs.scala]: So, yeah, I was trying to figure out before how to deal with errors in the midst of a chunked response. Like, is there some trailing header you can add (although I don’t know how/if you can do that with http4s currently)? Or, do you just terminate the connection, or do this and output an error.

The error output seems nice, but we have to document that clients will have to expect some particular output when it fails, and we probably need an funky delimiter to make sure it doesn’t just look like a CSV or JSON entry.

Comment (jdegoes) [inline web/src/main/scala/slamdata/engine/api/fs.scala]: I don't think we should do this, you should `flatMap` an error to `Process.fail`.

The right longer-term solution is to use HTTP chunked responses, which will allow for each chunk to succeed or error, which models the type signature exactly.

Comment (jdegoes) [inline web/src/main/scala/slamdata/engine/api/fs.scala]: Btw, embedding random text inside a document with a structured mime type will basically explode clients (not to mention, it's just a bad thing to do!).

Comment (sellout) [inline web/src/main/scala/slamdata/engine/api/fs.scala]: I thought using Process here got us chunked encoding already. And I couldn’t figure out how to have an “error” chunk. It just terminates the connection, right?

Comment (jdegoes) [inline web/src/main/scala/slamdata/engine/api/fs.scala]: > I thought using Process here got us chunked encoding already.

Very unlikely. That would have to be some http4s magic, haven't looked at the code or the way we're using it enough to say.

>  It just terminates the connection, right?

Yep, under HTTP 1.1 that's the best you can do.

Comment (mossprescott) [inline web/src/main/scala/slamdata/engine/api/fs.scala]: Yes, I will change it to just fail and see if I can document the behavior in a test. That was dumb.

Comment (mossprescott) [inline web/src/main/scala/slamdata/engine/api/fs.scala]: Playing around with curl, it looks like http4s uses `chunked`, but not until the response gets larger than 10KB or so.

If there's a delayed failure, http4s hangs for 30 seconds, then produces `200 OK` and writes the data that preceded the error. This is more or less the same thing it does if the `Task[Response]` is a failure. Actually, I don't think I'll bother with a test for that, because it's not good. But I still think it's the right thing for our code to do, at least for now.

**Comment by jdegoes** [comment]
@mossprescott Is this ready for final review / merge? This is holding up the 2.0.9 release which I need to get out.

**Comment by sellout** [comment]
Looks ready to me. I’ll merge.

I wish GitHub would let us know when commits are added to a PR, or when a new build finishes or something.
