### PR TITLE
Make aliases available when compiling sort keys.

### LINKED ISSUE #640: compiler: error with join and order by
The "synthetic" projection that we introduce for sorting is invalid in the presence of a join. For example, the following query:
```sql
select * from a left join b on a.id = b.id order by a.rank
```
Produces this error: `No table was defined in the scope of '__sd__0'`

### PR DESCRIPTION
**Pull request by sellout**
Fixes #640.

Also, fix ambiguous relation error so it doesn’t say “no table”.

### CODE REVIEW

File: core/src/main/scala/slamdata/engine/compiler.scala [hunk 1]
```diff
@@ -153,16 +153,16 @@ trait Compiler[F[_]] {
 
   private def invoke(func: Func, args: List[Node])(implicit m: Monad[F]): StateT[M, CompilerState, Term[LogicalPlan]] =
     for {
-      args <- args.map(compile0).sequenceU
+      args <- args.map(compile0(_, Nil)).sequenceU
     } yield func.apply(args: _*)
 
   // CORE COMPILER
-  private def compile0(node: Node)(implicit M: Monad[F]):
+  private def compile0(node: Node, aliases: List[String])(implicit M: Monad[F]):
```
Comment (jdegoes) [inline core/src/main/scala/slamdata/engine/compiler.scala]: Is this a list of aliases for the current node, or something else?

Comment (sellout) [inline core/src/main/scala/slamdata/engine/compiler.scala]: It’s a list of aliases _available to_ the current node. IE, if you look at line 392, you’ll see we add the names of the projections (actually, not only aliases – is that correct?) to the list when calling `compile0` on the sort keys.

Comment (sellout) [inline core/src/main/scala/slamdata/engine/compiler.scala]: If we find an ident in that list, we project relative to the rootTable, if it’s not, we look for the correct subtable to reference (as before).
