### PR TITLE
Convert SimpleMap flattens in a way that allows for stacked flattening.

### LINKED ISSUE #635: planner: flattening a flattened field is wrong
I’m not sure about this yet, so I’m making this keep track of it. I think
```sql
select parents[*]{*} from slamengine_commits
```
generates the wrong plan.

We get to the physical plan looking good:
```
Chain
├─ $Read(slamengine_commits)
├─ $Unwind(DocField(BsonField.Name("parents")))
├─ $SimpleFlatMap
│  ├─ Expr(_)
│  ├─ Flatten(_.parents)
│  ╰─ Scope(Map())
╰─ $Project
   ├─ Name(parents -> $parents)
   ╰─ IgnoreId
```

bu the map function below grabs both `elem1` and `elem0` from the unflattened parents field, so they’re both array indexes, and we only ever do one level of confused flattening.
```
db.slamengine_commits.mapReduce(
  function () {
    (function (key, value) {
      var rez = [];
      for (var elem1 in ((value != null) ? value.parents : undefined)) for (var elem0 in ((value != null) ? value.parents : undefined)) {
        var each = clone(value);
        (each != null) ? each.parents = ((value != null) && (value.parents != null)) ? value.parents[elem0] : undefined : undefined;
        (each != null) ? each.parents = ((value != null) && (value.parents != null)) ? value.parents[elem1] : undefined : undefined;
        ((rez != null) && (rez.push != null)) ? rez.push([ObjectId(), each]) : undefined
      };
      return rez
    })(
      this._id,
      this).map(
      function (__rez) { emit.apply(null, __rez) })
  },
  function (key, values) { return (values != null) ? values[0] : undefined },
  {
    "out": { "replace": "tmp.gen_0" },
    "scope": {
      "clone": function (src) {
        if (((typeof src) != "object") || (src == null)) return src;
        var dest = new src.constructor;
        for (var i in (src)) dest[i] = clone(src[i]);
        return dest
      }
    }
  });
db.tmp.gen_0.aggregate(
  [{ "$project": { "parents": "$value.parents" } }, { "$out": "tmp.gen_1" }],
  { "allowDiskUse": true });
db.tmp.gen_0.drop();
db.tmp.gen_1.find();
```

### PR DESCRIPTION
**Pull request by sellout**
Fixes #635.

### CODE REVIEW

File: core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala [hunk 1]
```diff
@@ -694,13 +694,13 @@ class WorkflowSpec extends Specification with TreeMatchers {
             Js.ForIn(Js.Ident("elem"), Select(Ident("value").fix, "loc").fix.toJs,
               Js.Block(List(
                 Js.VarDef(List(
-                  "each" -> Js.Call(Js.Ident("clone"), List(Js.Ident("value"))))),
-                safeAssign(Select(Ident("each").fix, "loc").fix, Access(Select(Ident("value").fix, "loc").fix, Ident("elem").fix).fix),
+                  "each0" -> Js.Call(Js.Ident("clone"), List(Js.Ident("value"))))),
```
Comment (jdegoes) [inline core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala]: Sometimes I think we should pretty print SlamScript using a syntax of our choosing and test against the pretty-printed version. Yeah, it's string testing, but I'd have more confidence the test is doing the right thing. No idea if this is correct!!

File: it/src/test/resources/tests/doubleFlatten.test [hunk 2]
```diff
@@ -1,6 +1,5 @@
 {
```
Comment (jdegoes) [inline it/src/test/resources/tests/doubleFlatten.test]: Just for the heck of it, can you do a triple flatten or something?

**Comment by jdegoes** [comment]
:+1: Looks good to me, would like another integration test in there and then will happily merge.

File: core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala (hunk 1 above)
Comment (mossprescott) [inline core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala]: I could not agree more. `JsMacro.toString` does something like `toUnsafeJs(_.simplify).render(0)`, which is easier to read, but not great for tests. We may eventually want a syntax for SlamScript anyway, so obviously we need an invertible parser.

File: core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala [hunk 3]
```diff
@@ -1138,18 +1138,20 @@ class WorkflowSpec extends Specification with TreeMatchers {
...
-                                Arr(List(
-                                  Call(Ident("ObjectId").fix, List[Term[JsCore]]()).fix,
-                                  Obj(ListMap(
-                                    "0" -> Select(Ident("each").fix, "bar").fix,
-                                    "1" -> Select(Ident("each").fix, "baz").fix)).fix)).fix)).fix.toJs)))),
+                        Js.ForIn(Js.Ident("elem"), JsCore.Select(Ident("value").fix, "bar").fix.toJs,
+                          Js.Block(List(
+                            Js.VarDef(List("each0" -> Js.Call(Js.Ident("clone"), List(Js.Ident("value"))))),
+                            JsCore.safeAssign(Select(Ident("each0").fix, "bar").fix, Access(Select(Ident("value").fix, "bar").fix, Ident("elem").fix).fix),
+                            Js.ForIn(Js.Ident("elem"), JsCore.Select(Ident("each0").fix, "baz").fix.toJs,
```
Comment (mossprescott) [inline core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala]: This is a *different* way of flattening multiple fields, but I can't see what was wrong with the old way (except that it must have had a bug). If generated JS coding style was something we were worried about, I'd say that shadowing `elem` is somewhat ugly, and you're making an unnecessary clone in the outer loop.

File: core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala (hunk 1 above)
Comment (sellout) [inline core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala]: Yes.

File: core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala (hunk 3 above)
Comment (sellout) [inline core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala]: I like the way you had written it, and I was thinking that it would be good to get that back in the future as a performance optimization when possible, but the important difference is how we handle stacked flattens (`parents[*]{*}`). which end up in the `$SimpleMap` `flatten` field as `[_.parents, _.parents]`.

The previous way walked over each expr in `flatten` and copied it from `value` to `each`, so in the `[*]{*}` case, it copied the entire parents object at each index twice, rather than the first flatten copying the object and the second copying a field from that object. In the `[*]{*}` case, the outer clone isn’t unnecessary – we need to hold the object that we later pull the fields from.

It would be nice to check the flattens, see which (if any) exprs overlap, and minimize the clones, pushing most of the flattens to the innermost loop (or pushing everything into the inner loop, but rewriting stacked expressions as necessary). But … these are arbitrary `JsMacro`s, so it’s not something I was about to dive into until we determine that flattening is a real problem for us.

I had actually not shadowed elem initially, but the scala code looked slightly nicer when I did – I’m happy to go back and change that, though.

File: it/src/test/resources/tests/doubleFlatten.test (hunk 2 above)
Comment (sellout) [inline it/src/test/resources/tests/doubleFlatten.test]: Do you know of any data sources with structures that deep? The most likely thing that comes to mind is something containing a matrix of objects, so we could do `foo[*][*]{*}`, intervening fields would be neat, too: `foo[*].bar[*]{*}`. But I don’t know where to find data this complicated.

File: core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala (hunk 3 above)
Comment (mossprescott) [inline core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala]: Note to self: read and understand the ticket then remember what it said before reviewing and commenting. Of course, that makes sense. Obviously we could optimize the common case of non-nested flattens, but I don't think it's important at this juncture.

File: core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala (hunk 1 above)
Comment (jdegoes) [inline core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala]: Obviously. :smiley:

File: it/src/test/resources/tests/doubleFlatten.test (hunk 2 above)
Comment (jdegoes) [inline it/src/test/resources/tests/doubleFlatten.test]: You know, I don't, but the facts database has many layers of nested objects, so you could probably do something like: `foo{*}.bar{*}.baz`, which would be at least or more interesting (you might even find 3 layers in there). If you can get something like that in there, I'll merge this in today.

Comment (sellout) [inline it/src/test/resources/tests/doubleFlatten.test]: Just checked – usa_factbook doesn’t give me anything deeper than `foo{*}{*}`, so even `foo{*}.bar{*}` is out of the question 😕

I guess I’ll just make a new data file with a few deeply-nested records. I think I also thought of a few more bugs to trigger with it 😉

**Comment by jdegoes** [comment]
Ready for merging or you want to fix the pending first? I'd open a ticket on the pending so I can get this in now, unless you're close to fixing.

**Comment by sellout** [comment]
Yeah, I'll open a ticket. It's orthogonal to this issue anyway.
