### PR TITLE
Fix some objectConcat errors.

### LINKED ISSUE #587: planner: objectConcat cannot handle unrecognized shapes
```sql
SELECT DISTINCT affiliations[*].orgRole, COUNT(*)
  FROM "/SampleArrayObjects" 
  GROUP BY affiliations[*].orgRole
```

Compile log:

```
Vector(SQL AST
Select(distinct)
+- Proj
¦  ?- Binop({})
¦     +- Unop(flatten_array)
¦     ¦  ?- Ident(affiliations)
¦     ?- LiteralExpr('orgRole')
+- Proj
¦  ?- InvokeFunction(COUNT)
¦     ?- Splice
+- TableRelation(/SampleArrayObjects)
?- GroupBy
   ?- Binop({})
      +- Unop(flatten_array)
      ¦  ?- Ident(affiliations)
      ?- LiteralExpr('orgRole'), SQL AST (paths interpreted)
Select(distinct)
+- Proj
¦  ?- Binop({})
¦     +- Unop(flatten_array)
¦     ¦  ?- Ident(affiliations)
¦     ?- LiteralExpr('orgRole')
+- Proj
¦  ?- InvokeFunction(COUNT)
¦     ?- Splice
+- TableRelation(./SampleArrayObjects)
?- GroupBy
   ?- Binop({})
      +- Unop(flatten_array)
      ¦  ?- Ident(affiliations)
      ?- LiteralExpr('orgRole'), Annotated Tree
Select(distinct)
+- Annotation
¦  +- None
¦  +- Provenance((./SampleArrayObjects & Value))
¦  +- None
¦  ?- Type(Product(NamedField(orgRole,Top),NamedField(1,Int)))
+- Proj
¦  +- Annotation
¦  ¦  +- None
¦  ¦  +- Provenance((./SampleArrayObjects & Value))
¦  ¦  +- None
¦  ¦  ?- Type(Top)
¦  ?- Binop({})
¦     +- Annotation
¦     ¦  +- None
¦     ¦  +- Provenance((./SampleArrayObjects & Value))
¦     ¦  +- OneToOne(({}))
¦     ¦  ?- Type(Top)
¦     +- Unop(flatten_array)
¦     ¦  +- Annotation
¦     ¦  ¦  +- None
¦     ¦  ¦  +- Provenance(./SampleArrayObjects)
¦     ¦  ¦  +- OneToManyFlat(FLATTEN_ARRAY)
¦     ¦  ¦  ?- Type(AnonField(Top))
¦     ¦  ?- Ident(affiliations)
¦     ¦     ?- Annotation
¦     ¦        +- None
¦     ¦        +- Provenance(./SampleArrayObjects)
¦     ¦        +- None
¦     ¦        ?- Type(AnonElem(AnonField(Top)))
¦     ?- LiteralExpr('orgRole')
¦        ?- Annotation
¦           +- None
¦           +- Provenance(Value)
¦           +- None
¦           ?- Type(Const(Data.Str("orgRole")))
+- Proj
¦  +- Annotation
¦  ¦  +- None
¦  ¦  +- Provenance(Empty)
¦  ¦  +- None
¦  ¦  ?- Type(Int)
¦  ?- InvokeFunction(COUNT)
¦     +- Annotation
¦     ¦  +- None
¦     ¦  +- Provenance(Empty)
¦     ¦  +- ManyToOne(COUNT)
¦     ¦  ?- Type(Int)
¦     ?- Splice
¦        ?- Annotation
¦           +- None
¦           +- Provenance(Empty)
¦           +- None
¦           ?- Type(Top)
+- TableRelation(./SampleArrayObjects)
¦  ?- Annotation
¦     +- None
¦     +- Provenance(./SampleArrayObjects)
¦     +- None
¦     ?- Type(Bottom)
?- GroupBy
   +- Annotation
   ¦  +- None
   ¦  +- Provenance((./SampleArrayObjects & Value))
   ¦  +- None
   ¦  ?- Type(IndexedElem(0,Top))
   ?- Binop({})
      +- Annotation
      ¦  +- None
      ¦  +- Provenance((./SampleArrayObjects & Value))
      ¦  +- OneToOne(({}))
      ¦  ?- Type(Top)
      +- Unop(flatten_array)
      ¦  +- Annotation
      ¦  ¦  +- None
      ¦  ¦  +- Provenance(./SampleArrayObjects)
      ¦  ¦  +- OneToManyFlat(FLATTEN_ARRAY)
      ¦  ¦  ?- Type(AnonField(Top))
      ¦  ?- Ident(affiliations)
      ¦     ?- Annotation
      ¦        +- None
      ¦        +- Provenance(./SampleArrayObjects)
      ¦        +- None
      ¦        ?- Type(AnonElem(AnonField(Top)))
      ?- LiteralExpr('orgRole')
         ?- Annotation
            +- None
            +- Provenance(Value)
            +- None
            ?- Type(Const(Data.Str("orgRole"))), Annotated Tree (variables substituted)
Select(distinct)
+- Annotation
¦  +- None
¦  +- Provenance((./SampleArrayObjects & Value))
¦  +- None
¦  ?- Type(Product(NamedField(orgRole,Top),NamedField(1,Int)))
+- Proj
¦  +- Annotation
¦  ¦  +- None
¦  ¦  +- Provenance((./SampleArrayObjects & Value))
¦  ¦  +- None
¦  ¦  ?- Type(Top)
¦  ?- Binop({})
¦     +- Annotation
¦     ¦  +- None
¦     ¦  +- Provenance((./SampleArrayObjects & Value))
¦     ¦  +- OneToOne(({}))
¦     ¦  ?- Type(Top)
¦     +- Unop(flatten_array)
¦     ¦  +- Annotation
¦     ¦  ¦  +- None
¦     ¦  ¦  +- Provenance(./SampleArrayObjects)
¦     ¦  ¦  +- OneToManyFlat(FLATTEN_ARRAY)
¦     ¦  ¦  ?- Type(AnonField(Top))
¦     ¦  ?- Ident(affiliations)
¦     ¦     ?- Annotation
¦     ¦        +- None
¦     ¦        +- Provenance(./SampleArrayObjects)
¦     ¦        +- None
¦     ¦        ?- Type(AnonElem(AnonField(Top)))
¦     ?- LiteralExpr('orgRole')
¦        ?- Annotation
¦           +- None
¦           +- Provenance(Value)
¦           +- None
¦           ?- Type(Const(Data.Str("orgRole")))
+- Proj
¦  +- Annotation
¦  ¦  +- None
¦  ¦  +- Provenance(Empty)
¦  ¦  +- None
¦  ¦  ?- Type(Int)
¦  ?- InvokeFunction(COUNT)
¦     +- Annotation
¦     ¦  +- None
¦     ¦  +- Provenance(Empty)
¦     ¦  +- ManyToOne(COUNT)
¦     ¦  ?- Type(Int)
¦     ?- Splice
¦        ?- Annotation
¦           +- None
¦           +- Provenance(Empty)
¦           +- None
¦           ?- Type(Top)
+- TableRelation(./SampleArrayObjects)
¦  ?- Annotation
¦     +- None
¦     +- Provenance(./SampleArrayObjects)
¦     +- None
¦     ?- Type(Bottom)
?- GroupBy
   +- Annotation
   ¦  +- None
   ¦  +- Provenance((./SampleArrayObjects & Value))
   ¦  +- None
   ¦  ?- Type(IndexedElem(0,Top))
   ?- Binop({})
      +- Annotation
      ¦  +- None
      ¦  +- Provenance((./SampleArrayObjects & Value))
      ¦  +- OneToOne(({}))
      ¦  ?- Type(Top)
      +- Unop(flatten_array)
      ¦  +- Annotation
      ¦  ¦  +- None
      ¦  ¦  +- Provenance(./SampleArrayObjects)
      ¦  ¦  +- OneToManyFlat(FLATTEN_ARRAY)
      ¦  ¦  ?- Type(AnonField(Top))
      ¦  ?- Ident(affiliations)
      ¦     ?- Annotation
      ¦        +- None
      ¦        +- Provenance(./SampleArrayObjects)
      ¦        +- None
      ¦        ?- Type(AnonElem(AnonField(Top)))
      ?- LiteralExpr('orgRole')
         ?- Annotation
            +- None
            +- Provenance(Value)
            +- None
            ?- Type(Const(Data.Str("orgRole"))), Logical Plan
Let('tmp0)
+- Read(./SampleArrayObjects)
?- Let('tmp1)
   +- ManyToMany(GROUP BY)
   ¦  +- Free('tmp0)
   ¦  ?- OneToOne(MAKE_ARRAY)
   ¦     ?- OneToOne(({}))
   ¦        +- OneToManyFlat(FLATTEN_ARRAY)
   ¦        ¦  ?- OneToOne(({}))
   ¦        ¦     +- Free('tmp0)
   ¦        ¦     ?- Constant(Data.Str("affiliations"))
   ¦        ?- Constant(Data.Str("orgRole"))
   ?- Let('tmp2)
      +- OneToOne(OBJECT_CONCAT)
      ¦  +- OneToOne(MAKE_OBJECT)
      ¦  ¦  +- Constant(Data.Str("orgRole"))
      ¦  ¦  ?- OneToOne(({}))
      ¦  ¦     +- OneToManyFlat(FLATTEN_ARRAY)
      ¦  ¦     ¦  ?- OneToOne(({}))
      ¦  ¦     ¦     +- Free('tmp1)
      ¦  ¦     ¦     ?- Constant(Data.Str("affiliations"))
      ¦  ¦     ?- Constant(Data.Str("orgRole"))
      ¦  ?- OneToOne(MAKE_OBJECT)
      ¦     +- Constant(Data.Str("1"))
      ¦     ?- ManyToOne(COUNT)
      ¦        ?- Free('tmp1)
      ?- Let('tmp3)
         +- Squashing(SQUASH)
         ¦  ?- Free('tmp2)
         ?- Let('tmp4)
            +- ManyToMany(DISTINCT)
            ¦  ?- Free('tmp3)
            ?- Free('tmp4), Simplified
Let('tmp0)
+- Read(./SampleArrayObjects)
?- Let('tmp1)
   +- ManyToMany(GROUP BY)
   ¦  +- Free('tmp0)
   ¦  ?- OneToOne(MAKE_ARRAY)
   ¦     ?- OneToOne(({}))
   ¦        +- OneToManyFlat(FLATTEN_ARRAY)
   ¦        ¦  ?- OneToOne(({}))
   ¦        ¦     +- Free('tmp0)
   ¦        ¦     ?- Constant(Data.Str("affiliations"))
   ¦        ?- Constant(Data.Str("orgRole"))
   ?- ManyToMany(DISTINCT)
      ?- Squashing(SQUASH)
         ?- OneToOne(OBJECT_CONCAT)
            +- OneToOne(MAKE_OBJECT)
            ¦  +- Constant(Data.Str("orgRole"))
            ¦  ?- OneToOne(({}))
            ¦     +- OneToManyFlat(FLATTEN_ARRAY)
            ¦     ¦  ?- OneToOne(({}))
            ¦     ¦     +- Free('tmp1)
            ¦     ¦     ?- Constant(Data.Str("affiliations"))
            ¦     ?- Constant(Data.Str("orgRole"))
            ?- OneToOne(MAKE_OBJECT)
               +- Constant(Data.Str("1"))
               ?- ManyToOne(COUNT)
                  ?- Free('tmp1), Physical Plan
Can not perform `objectConcat`, because unrecognized shapes:
DocBuilder
+- FlatteningBuilder
¦  +- GroupBuilder
¦  ¦  +- CollectionBuilder
¦  ¦  ¦  +- Chain
¦  ¦  ¦  ¦  +- $Read(SampleArrayObjects)
¦  ¦  ¦  ¦  +- $Project
¦  ¦  ¦  ¦  ¦  +- Name(__tmp0 -> $$ROOT)
¦  ¦  ¦  ¦  ¦  +- Name(__tmp1 -> $$ROOT)
¦  ¦  ¦  ¦  ¦  ?- IgnoreId
¦  ¦  ¦  ¦  ?- $Unwind(DocField(BsonField.Name("__tmp0") \ BsonField.Name("affiliations")))
¦  ¦  ¦  +- ExprOp(DocVar.ROOT())
¦  ¦  ¦  ?- SchemaChange(Init)
¦  ¦  +- By(-\/(DocField(BsonField.Name("__tmp0") \ BsonField.Name("affiliations") \ BsonField.Name("orgRole"))))
¦  ¦  +- Content
¦  ¦  ¦  ?- -\/
¦  ¦  ¦     ?- ExprOp(DocField(BsonField.Name("__tmp1") \ BsonField.Name("affiliations")))
¦  ¦  ?- Id(76df656b)
¦  +- Type(Array)
¦  ?- ExprOp(DocVar.ROOT())
?- Shape
   ?- ExprOp(orgRole -> DocField(BsonField.Name("orgRole")))
GroupBuilder
+- CollectionBuilder
¦  +- Chain
¦  ¦  +- $Read(SampleArrayObjects)
¦  ¦  +- $Project
¦  ¦  ¦  +- Name(__tmp0 -> $$ROOT)
¦  ¦  ¦  +- Name(__tmp1 -> $$ROOT)
¦  ¦  ¦  ?- IgnoreId
¦  ¦  ?- $Unwind(DocField(BsonField.Name("__tmp0") \ BsonField.Name("affiliations")))
¦  +- ExprOp(DocVar.ROOT())
¦  ?- SchemaChange(Init)
+- By(-\/(DocField(BsonField.Name("__tmp0") \ BsonField.Name("affiliations") \ BsonField.Name("orgRole"))))
+- Content
¦  ?- Map
¦     ?- BsonField.Name("1")
¦        ?- \/-
¦           ?- GroupOp(Sum(Literal(Int32(1))))
?- Id(76df656b)
slamdata.engine.physical.mongodb.WorkflowBuilder$.objectConcat(workflowbuilder.scala:804)
slamdata.engine.physical.mongodb.MongoDbPlanner$$anonfun$slamdata$engine$physical$mongodb$MongoDbPlanner$$invoke$3$3.apply(planner.scala:575)
slamdata.engine.physical.mongodb.MongoDbPlanner$$anonfun$slamdata$engine$physical$mongodb$MongoDbPlanner$$invoke$3$3.apply(planner.scala:575)
  ... (11)
slamdata.engine.physical.mongodb.MongoDbPlanner$$anonfun$WorkflowPhase$1$$anonfun$apply$96$$anonfun$apply$97.apply(planner.scala:797)
slamdata.engine.physical.mongodb.MongoDbPlanner$$anonfun$WorkflowPhase$1$$anonfun$apply$96$$anonfun$apply$97.apply(planner.scala:797)
  ... (62)
slamdata.engine.physical.mongodb.WorkflowBuilder$$anonfun$swapM$1.apply(workflowbuilder.scala:199)
slamdata.engine.physical.mongodb.WorkflowBuilder$$anonfun$swapM$1.apply(workflowbuilder.scala:199)
  ... (7)
slamdata.engine.physical.mongodb.MongoDbPlanner$.plan(planner.scala:816)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(planner.scala:58)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(planner.scala:57)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7.apply(planner.scala:57)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7.apply(planner.scala:56)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6.apply(planner.scala:56)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6.apply(planner.scala:55)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4.apply(planner.scala:55)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4.apply(planner.scala:54)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2.apply(planner.scala:54)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2.apply(planner.scala:53)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1.apply(planner.scala:53)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1.apply(planner.scala:52)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1.apply(planner.scala:52)
slamdata.engine.Planner$$anonfun$queryPlanner$1.apply(planner.scala:46)
slamdata.engine.Backend$$anon$2.run(backend.scala:119)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1$$anonfun$apply$9$$anonfun$apply$10.apply(admin.scala:186)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1$$anonfun$apply$9$$anonfun$apply$10.apply(admin.scala:186)
  ... (2)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1$$anonfun$apply$9.apply(admin.scala:186)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1$$anonfun$apply$9.apply(admin.scala:185)
  ... (1)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1.apply(admin.scala:185)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1.apply(admin.scala:183)
  ... (1)
slamdata.engine.admin.AdminUI$$anon$8.planQuery(admin.scala:183)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$runAction$1.apply$mcV$sp(admin.scala:148)
  ... (38))

SQL AST
Select(distinct)
+- Proj
¦  ?- Binop({})
¦     +- Unop(flatten_array)
¦     ¦  ?- Ident(affiliations)
¦     ?- LiteralExpr('orgRole')
+- Proj
¦  ?- InvokeFunction(COUNT)
¦     ?- Splice
+- TableRelation(/SampleArrayObjects)
?- GroupBy
   ?- Binop({})
      +- Unop(flatten_array)
      ¦  ?- Ident(affiliations)
      ?- LiteralExpr('orgRole')

SQL AST (paths interpreted)
Select(distinct)
+- Proj
¦  ?- Binop({})
¦     +- Unop(flatten_array)
¦     ¦  ?- Ident(affiliations)
¦     ?- LiteralExpr('orgRole')
+- Proj
¦  ?- InvokeFunction(COUNT)
¦     ?- Splice
+- TableRelation(./SampleArrayObjects)
?- GroupBy
   ?- Binop({})
      +- Unop(flatten_array)
      ¦  ?- Ident(affiliations)
      ?- LiteralExpr('orgRole')

Annotated Tree
Select(distinct)
+- Annotation
¦  +- None
¦  +- Provenance((./SampleArrayObjects & Value))
¦  +- None
¦  ?- Type(Product(NamedField(orgRole,Top),NamedField(1,Int)))
+- Proj
¦  +- Annotation
¦  ¦  +- None
¦  ¦  +- Provenance((./SampleArrayObjects & Value))
¦  ¦  +- None
¦  ¦  ?- Type(Top)
¦  ?- Binop({})
¦     +- Annotation
¦     ¦  +- None
¦     ¦  +- Provenance((./SampleArrayObjects & Value))
¦     ¦  +- OneToOne(({}))
¦     ¦  ?- Type(Top)
¦     +- Unop(flatten_array)
¦     ¦  +- Annotation
¦     ¦  ¦  +- None
¦     ¦  ¦  +- Provenance(./SampleArrayObjects)
¦     ¦  ¦  +- OneToManyFlat(FLATTEN_ARRAY)
¦     ¦  ¦  ?- Type(AnonField(Top))
¦     ¦  ?- Ident(affiliations)
¦     ¦     ?- Annotation
¦     ¦        +- None
¦     ¦        +- Provenance(./SampleArrayObjects)
¦     ¦        +- None
¦     ¦        ?- Type(AnonElem(AnonField(Top)))
¦     ?- LiteralExpr('orgRole')
¦        ?- Annotation
¦           +- None
¦           +- Provenance(Value)
¦           +- None
¦           ?- Type(Const(Data.Str("orgRole")))
+- Proj
¦  +- Annotation
¦  ¦  +- None
¦  ¦  +- Provenance(Empty)
¦  ¦  +- None
¦  ¦  ?- Type(Int)
¦  ?- InvokeFunction(COUNT)
¦     +- Annotation
¦     ¦  +- None
¦     ¦  +- Provenance(Empty)
¦     ¦  +- ManyToOne(COUNT)
¦     ¦  ?- Type(Int)
¦     ?- Splice
¦        ?- Annotation
¦           +- None
¦           +- Provenance(Empty)
¦           +- None
¦           ?- Type(Top)
+- TableRelation(./SampleArrayObjects)
¦  ?- Annotation
¦     +- None
¦     +- Provenance(./SampleArrayObjects)
¦     +- None
¦     ?- Type(Bottom)
?- GroupBy
   +- Annotation
   ¦  +- None
   ¦  +- Provenance((./SampleArrayObjects & Value))
   ¦  +- None
   ¦  ?- Type(IndexedElem(0,Top))
   ?- Binop({})
      +- Annotation
      ¦  +- None
      ¦  +- Provenance((./SampleArrayObjects & Value))
      ¦  +- OneToOne(({}))
      ¦  ?- Type(Top)
      +- Unop(flatten_array)
      ¦  +- Annotation
      ¦  ¦  +- None
      ¦  ¦  +- Provenance(./SampleArrayObjects)
      ¦  ¦  +- OneToManyFlat(FLATTEN_ARRAY)
      ¦  ¦  ?- Type(AnonField(Top))
      ¦  ?- Ident(affiliations)
      ¦     ?- Annotation
      ¦        +- None
      ¦        +- Provenance(./SampleArrayObjects)
      ¦        +- None
      ¦        ?- Type(AnonElem(AnonField(Top)))
      ?- LiteralExpr('orgRole')
         ?- Annotation
            +- None
            +- Provenance(Value)
            +- None
            ?- Type(Const(Data.Str("orgRole")))

Annotated Tree (variables substituted)
Select(distinct)
+- Annotation
¦  +- None
¦  +- Provenance((./SampleArrayObjects & Value))
¦  +- None
¦  ?- Type(Product(NamedField(orgRole,Top),NamedField(1,Int)))
+- Proj
¦  +- Annotation
¦  ¦  +- None
¦  ¦  +- Provenance((./SampleArrayObjects & Value))
¦  ¦  +- None
¦  ¦  ?- Type(Top)
¦  ?- Binop({})
¦     +- Annotation
¦     ¦  +- None
¦     ¦  +- Provenance((./SampleArrayObjects & Value))
¦     ¦  +- OneToOne(({}))
¦     ¦  ?- Type(Top)
¦     +- Unop(flatten_array)
¦     ¦  +- Annotation
¦     ¦  ¦  +- None
¦     ¦  ¦  +- Provenance(./SampleArrayObjects)
¦     ¦  ¦  +- OneToManyFlat(FLATTEN_ARRAY)
¦     ¦  ¦  ?- Type(AnonField(Top))
¦     ¦  ?- Ident(affiliations)
¦     ¦     ?- Annotation
¦     ¦        +- None
¦     ¦        +- Provenance(./SampleArrayObjects)
¦     ¦        +- None
¦     ¦        ?- Type(AnonElem(AnonField(Top)))
¦     ?- LiteralExpr('orgRole')
¦        ?- Annotation
¦           +- None
¦           +- Provenance(Value)
¦           +- None
¦           ?- Type(Const(Data.Str("orgRole")))
+- Proj
¦  +- Annotation
¦  ¦  +- None
¦  ¦  +- Provenance(Empty)
¦  ¦  +- None
¦  ¦  ?- Type(Int)
¦  ?- InvokeFunction(COUNT)
¦     +- Annotation
¦     ¦  +- None
¦     ¦  +- Provenance(Empty)
¦     ¦  +- ManyToOne(COUNT)
¦     ¦  ?- Type(Int)
¦     ?- Splice
¦        ?- Annotation
¦           +- None
¦           +- Provenance(Empty)
¦           +- None
¦           ?- Type(Top)
+- TableRelation(./SampleArrayObjects)
¦  ?- Annotation
¦     +- None
¦     +- Provenance(./SampleArrayObjects)
¦     +- None
¦     ?- Type(Bottom)
?- GroupBy
   +- Annotation
   ¦  +- None
   ¦  +- Provenance((./SampleArrayObjects & Value))
   ¦  +- None
   ¦  ?- Type(IndexedElem(0,Top))
   ?- Binop({})
      +- Annotation
      ¦  +- None
      ¦  +- Provenance((./SampleArrayObjects & Value))
      ¦  +- OneToOne(({}))
      ¦  ?- Type(Top)
      +- Unop(flatten_array)
      ¦  +- Annotation
      ¦  ¦  +- None
      ¦  ¦  +- Provenance(./SampleArrayObjects)
      ¦  ¦  +- OneToManyFlat(FLATTEN_ARRAY)
      ¦  ¦  ?- Type(AnonField(Top))
      ¦  ?- Ident(affiliations)
      ¦     ?- Annotation
      ¦        +- None
      ¦        +- Provenance(./SampleArrayObjects)
      ¦        +- None
      ¦        ?- Type(AnonElem(AnonField(Top)))
      ?- LiteralExpr('orgRole')
         ?- Annotation
            +- None
            +- Provenance(Value)
            +- None
            ?- Type(Const(Data.Str("orgRole")))

Logical Plan
Let('tmp0)
+- Read(./SampleArrayObjects)
?- Let('tmp1)
   +- ManyToMany(GROUP BY)
   ¦  +- Free('tmp0)
   ¦  ?- OneToOne(MAKE_ARRAY)
   ¦     ?- OneToOne(({}))
   ¦        +- OneToManyFlat(FLATTEN_ARRAY)
   ¦        ¦  ?- OneToOne(({}))
   ¦        ¦     +- Free('tmp0)
   ¦        ¦     ?- Constant(Data.Str("affiliations"))
   ¦        ?- Constant(Data.Str("orgRole"))
   ?- Let('tmp2)
      +- OneToOne(OBJECT_CONCAT)
      ¦  +- OneToOne(MAKE_OBJECT)
      ¦  ¦  +- Constant(Data.Str("orgRole"))
      ¦  ¦  ?- OneToOne(({}))
      ¦  ¦     +- OneToManyFlat(FLATTEN_ARRAY)
      ¦  ¦     ¦  ?- OneToOne(({}))
      ¦  ¦     ¦     +- Free('tmp1)
      ¦  ¦     ¦     ?- Constant(Data.Str("affiliations"))
      ¦  ¦     ?- Constant(Data.Str("orgRole"))
      ¦  ?- OneToOne(MAKE_OBJECT)
      ¦     +- Constant(Data.Str("1"))
      ¦     ?- ManyToOne(COUNT)
      ¦        ?- Free('tmp1)
      ?- Let('tmp3)
         +- Squashing(SQUASH)
         ¦  ?- Free('tmp2)
         ?- Let('tmp4)
            +- ManyToMany(DISTINCT)
            ¦  ?- Free('tmp3)
            ?- Free('tmp4)

Simplified
Let('tmp0)
+- Read(./SampleArrayObjects)
?- Let('tmp1)
   +- ManyToMany(GROUP BY)
   ¦  +- Free('tmp0)
   ¦  ?- OneToOne(MAKE_ARRAY)
   ¦     ?- OneToOne(({}))
   ¦        +- OneToManyFlat(FLATTEN_ARRAY)
   ¦        ¦  ?- OneToOne(({}))
   ¦        ¦     +- Free('tmp0)
   ¦        ¦     ?- Constant(Data.Str("affiliations"))
   ¦        ?- Constant(Data.Str("orgRole"))
   ?- ManyToMany(DISTINCT)
      ?- Squashing(SQUASH)
         ?- OneToOne(OBJECT_CONCAT)
            +- OneToOne(MAKE_OBJECT)
            ¦  +- Constant(Data.Str("orgRole"))
            ¦  ?- OneToOne(({}))
            ¦     +- OneToManyFlat(FLATTEN_ARRAY)
            ¦     ¦  ?- OneToOne(({}))
            ¦     ¦     +- Free('tmp1)
            ¦     ¦     ?- Constant(Data.Str("affiliations"))
            ¦     ?- Constant(Data.Str("orgRole"))
            ?- OneToOne(MAKE_OBJECT)
               +- Constant(Data.Str("1"))
               ?- ManyToOne(COUNT)
                  ?- Free('tmp1)

Physical Plan
Can not perform `objectConcat`, because unrecognized shapes:
DocBuilder
+- FlatteningBuilder
¦  +- GroupBuilder
¦  ¦  +- CollectionBuilder
¦  ¦  ¦  +- Chain
¦  ¦  ¦  ¦  +- $Read(SampleArrayObjects)
¦  ¦  ¦  ¦  +- $Project
¦  ¦  ¦  ¦  ¦  +- Name(__tmp0 -> $$ROOT)
¦  ¦  ¦  ¦  ¦  +- Name(__tmp1 -> $$ROOT)
¦  ¦  ¦  ¦  ¦  ?- IgnoreId
¦  ¦  ¦  ¦  ?- $Unwind(DocField(BsonField.Name("__tmp0") \ BsonField.Name("affiliations")))
¦  ¦  ¦  +- ExprOp(DocVar.ROOT())
¦  ¦  ¦  ?- SchemaChange(Init)
¦  ¦  +- By(-\/(DocField(BsonField.Name("__tmp0") \ BsonField.Name("affiliations") \ BsonField.Name("orgRole"))))
¦  ¦  +- Content
¦  ¦  ¦  ?- -\/
¦  ¦  ¦     ?- ExprOp(DocField(BsonField.Name("__tmp1") \ BsonField.Name("affiliations")))
¦  ¦  ?- Id(76df656b)
¦  +- Type(Array)
¦  ?- ExprOp(DocVar.ROOT())
?- Shape
   ?- ExprOp(orgRole -> DocField(BsonField.Name("orgRole")))
GroupBuilder
+- CollectionBuilder
¦  +- Chain
¦  ¦  +- $Read(SampleArrayObjects)
¦  ¦  +- $Project
¦  ¦  ¦  +- Name(__tmp0 -> $$ROOT)
¦  ¦  ¦  +- Name(__tmp1 -> $$ROOT)
¦  ¦  ¦  ?- IgnoreId
¦  ¦  ?- $Unwind(DocField(BsonField.Name("__tmp0") \ BsonField.Name("affiliations")))
¦  +- ExprOp(DocVar.ROOT())
¦  ?- SchemaChange(Init)
+- By(-\/(DocField(BsonField.Name("__tmp0") \ BsonField.Name("affiliations") \ BsonField.Name("orgRole"))))
+- Content
¦  ?- Map
¦     ?- BsonField.Name("1")
¦        ?- \/-
¦           ?- GroupOp(Sum(Literal(Int32(1))))
?- Id(76df656b)
slamdata.engine.physical.mongodb.WorkflowBuilder$.objectConcat(workflowbuilder.scala:804)
slamdata.engine.physical.mongodb.MongoDbPlanner$$anonfun$slamdata$engine$physical$mongodb$MongoDbPlanner$$invoke$3$3.apply(planner.scala:575)
slamdata.engine.physical.mongodb.MongoDbPlanner$$anonfun$slamdata$engine$physical$mongodb$MongoDbPlanner$$invoke$3$3.apply(planner.scala:575)
  ... (11)
slamdata.engine.physical.mongodb.MongoDbPlanner$$anonfun$WorkflowPhase$1$$anonfun$apply$96$$anonfun$apply$97.apply(planner.scala:797)
slamdata.engine.physical.mongodb.MongoDbPlanner$$anonfun$WorkflowPhase$1$$anonfun$apply$96$$anonfun$apply$97.apply(planner.scala:797)
  ... (62)
slamdata.engine.physical.mongodb.WorkflowBuilder$$anonfun$swapM$1.apply(workflowbuilder.scala:199)
slamdata.engine.physical.mongodb.WorkflowBuilder$$anonfun$swapM$1.apply(workflowbuilder.scala:199)
  ... (7)
slamdata.engine.physical.mongodb.MongoDbPlanner$.plan(planner.scala:816)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(planner.scala:58)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(planner.scala:57)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7.apply(planner.scala:57)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7.apply(planner.scala:56)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6.apply(planner.scala:56)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6.apply(planner.scala:55)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4.apply(planner.scala:55)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4.apply(planner.scala:54)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2.apply(planner.scala:54)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1$$anonfun$apply$2.apply(planner.scala:53)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1.apply(planner.scala:53)
slamdata.engine.Planner$$anonfun$queryPlanner$1$$anonfun$apply$1.apply(planner.scala:52)
  ... (12)
slamdata.engine.Planner$$anonfun$queryPlanner$1.apply(planner.scala:52)
slamdata.engine.Planner$$anonfun$queryPlanner$1.apply(planner.scala:46)
slamdata.engine.Backend$$anon$2.run(backend.scala:119)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1$$anonfun$apply$9$$anonfun$apply$10.apply(admin.scala:186)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1$$anonfun$apply$9$$anonfun$apply$10.apply(admin.scala:186)
  ... (2)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1$$anonfun$apply$9.apply(admin.scala:186)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1$$anonfun$apply$9.apply(admin.scala:185)
  ... (1)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1.apply(admin.scala:185)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$planQuery$1.apply(admin.scala:183)
  ... (1)
slamdata.engine.admin.AdminUI$$anon$8.planQuery(admin.scala:183)
slamdata.engine.admin.AdminUI$$anon$8$$anonfun$runAction$1.apply$mcV$sp(admin.scala:148)
  ... (38)
```

### PR DESCRIPTION
**Pull request by sellout**
Fixes #587.

* Fix $SimpleFlatMap composition,
* handle a missed merge case, and
* pass `objectConcat` through empty GroupBuilders.

### CODE REVIEW

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala [hunk 1]
```diff
@@ -830,6 +829,11 @@ object WorkflowBuilder {
       // approach, which we don't know to be correct and efficient in all cases.
       case (CollectionBuilderF(_, _, _), _) => generalMerge
       case (_, CollectionBuilderF(_, _, _)) => generalMerge
+      case (
+        GroupBuilderF(src1, keys, Expr(-\/(DocVar.ROOT(_))), id1),
+        GroupBuilderF(src2, _,    Expr(-\/(DocVar.ROOT(_))), id2))
+          if id1 == id2 =>
+        objectConcat(src1, src2).map(GroupBuilder(_, keys, Expr(-\/(DocVar.ROOT())), id1))
```
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: Why is this case in the middle of the generalMerge cases, as opposed to higher up with the rest of the GroupBuilder cases?

What makes this stuff hard to follow is when the patterns overlap, and therefore the cases have to be in a certain order. When you put one down low like this, it makes me wonder about that, but that doesn't actually seem to be the case here (sorry about the pun).

**Comment by mossprescott** [comment]
Looks good except for the one question.

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala (hunk 1 above)
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala]: Yep, I’ll move it up. I had originally added a generalMerge case for the GroupBuilders, but it morphed into this and I just didn’t put it back in the right spot.
