### PR TITLE
validate MongoDB connection URI before updating config

### LINKED ISSUE #758: host:port error
1. User enters connection information in SlamData.
2. Cannot connect.
3. User restarts.
4. Error message below prints out.

There may be a problem on the front-end, too -- in fact, I suspect there is -- please report that as well if it turns out to be the case.

Probably the API allows storage of incorrect / invalid URI data, which explodes the server on restart. The API should not allow adding mounts unless they are valid.

I will work with the user to get the structure of the Connection URI.

```
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.simontuffs.onejar.Boot.run(Boot.java:340)
at com.simontuffs.onejar.Boot.main(Boot.java:166)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
at com.install4j.runtime.launcher.MacLauncher.main(Unknown Source)
Caused by: com.mongodb.MongoException: host and port should be specified in host:port format
at com.mongodb.ServerAddress.<init>(ServerAddress.java:122)
at com.mongodb.ServerAddress.<init>(ServerAddress.java:49)
at com.mongodb.Mongo.createCluster(Mongo.java:618)
at com.mongodb.Mongo.<init>(Mongo.java:283)
at com.mongodb.MongoClient.<init>(MongoClient.java:265)
at slamdata.engine.physical.mongodb.util$$anonfun$1.apply(util.scala:13)
at slamdata.engine.physical.mongodb.util$$anonfun$1.apply(util.scala:12)
at scalaz.MemoFunctions$$anonfun$mutableMapMemo$1$$anonfun$apply$2$$anonfun$apply$3.apply(Memo.scala:67)
at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
at scalaz.MemoFunctions$$anonfun$mutableMapMemo$1$$anonfun$apply$2.apply(Memo.scala:67)
at slamdata.engine.physical.mongodb.util$$anonfun$2$$anonfun$apply$1.apply(util.scala:16)
at slamdata.engine.physical.mongodb.util$$anonfun$2$$anonfun$apply$1.apply(util.scala:16)
at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:274)
at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:274)
at scalaz.concurrent.Task$.Try(Task.scala:379)
at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:274)
at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:274)
at scalaz.concurrent.Future.step(Future.scala:111)
at scalaz.concurrent.Future.listen(Future.scala:76)
at scalaz.concurrent.Future.runAsync(Future.scala:143)
at scalaz.concurrent.Future.run(Future.scala:160)
at scalaz.concurrent.Task.run(Task.scala:97)
at slamdata.engine.api.Server$.main(server.scala:120)
at slamdata.engine.api.Server.main(server.scala)
... 12 more
```

### PR DESCRIPTION
**Pull request by mossprescott**
Fixes #758.

Static validation for MongoDbConfig that just attempts to parse the connection
URI.

Fix our parser to reject URIs with extra slashes, to match MongoDBs behavior.
Note: we may want two parsers at some point; one to decipher user-entered
URIs, which is lenient, and another to validate URIs from the API, which is
strict. We would regularize user-entered URIs so that they pass the strict
parser before saving them.

Small-scale conversion in the API to `EitherT[Task, RequestError, A]` to deal
with this one case.

Expose the raw services and separately a mapping from paths to the same
services wrapped in our common middleware.

New middleware to deal with failure in `Task`, returning a 500 with the
description wrapped in Json. This fixes the annoying default behavior of
http4s, which is to hang for 30 seconds and then return an empty 200.

### CODE REVIEW

**Comment by jdegoes** [comment]
@sellout Can we get a review / merge here?

File: web/src/main/scala/slamdata/engine/api/fs.scala [hunk 1]
```diff
@@ -451,8 +477,18 @@ class FileSystemApi(fs: FSTable[Backend]) {
...
+
+  def AllServices = ListMap(
+    "/compile/fs"  -> FailSafe(Cors(compileService)),
+    "/data/fs"     -> FailSafe(Cors(dataService)),
+    "/metadata/fs" -> FailSafe(Cors(metadataService)),
+    "/mount/fs"    -> FailSafe(Cors(mountService(config, reloader))),
+    "/query/fs"    -> FailSafe(Cors(queryService)),
+    "/server"      -> FailSafe(Cors(serverService(config, reloader))),
+    "/slamdata"    -> FailSafe(Cors(staticFileService(contentPath + "/slamdata"))),
+    "/"            -> FailSafe(Cors(redirectService("/slamdata"))))
```
Comment (sellout) [inline web/src/main/scala/slamdata/engine/api/fs.scala]: I like this – both moving the service mapping and the FailSafe and Cors objects. 👍🏾
