### PR TITLE
handle splicing in objectConcat (fixes #497)

### LINKED ISSUE #497: mongodb: runtime error with wildcard and more than one other field
```sql
select *, city, pop
  from zips
  where pop > 1000
```
gives `java.lang.RuntimeException: cannot merge class slamdata.engine.physical.mongodb.Workflow$$Map with class slamdata.engine.physical.mongodb.Workflow$$Match`.

The same query with just `select *, city` works as expected.

### PR DESCRIPTION
**Pull request by mossprescott**
Added a primitive `Splice` expression to JsCore, which encapsulates the
JavaScript machinery as a pure computation. This allows splicing to be
handled by SimpleMap. Also implemented the missing cases in objectConcat
for SpliceBuilders.

That resulted in Simple(Flat)Maps showing up in more places, including after
the unwinds introduced by joins, exposing the fact that successive
SimpleFlatMap ops were not composed in a sensible way. The simplest fix was
extending SimpleFlatMap to handle a list of flattened values. Since
a SimpleFlatMap with an empty list of flattened fields is equivalent to
SimpleMap, just went for it and collapsed the two ops into one, with a
potentially empty list of fields to be flattened.

The new SimpleMap is not as clean and, well, simple, as the old SimpleMap,
but it's more general than the old SimpleFlatMap, so on net it's an improvement.
We could get even more generality by making the "flattening" operation
an arbitrary expression, but it would be tricky to get equally clean, efficient JS.

Slightly improved handling of SimpleMap in the RenderTree instance, making it
more obvious what's what.

Now collapsing ExprBuilders in expr2, so the shape is more
consistent when it arrives in objectConcat. You can still get stacked
ExprBuilders in some cases, however, such as when a JS expression is built on
an ExprOp.

### CODE REVIEW

File: core/src/main/scala/slamdata/engine/javascript/jscore.scala [hunk 1]
```diff
@@ -205,6 +219,16 @@ object JsCore {
...
+
+      case s @ Splice(srcs)    =>
+        val tmp = Ident("__rez")  // TODO: use properly-generated temp name (see #581)
+        Js.Let(
+          Map(tmp.name -> Js.AnonObjDecl(Nil)), 
+          srcs.flatMap {
+            case Term(Obj(values)) => values.map { case (k, v) => Js.BinOp("=", smartDeref(tmp.fix.toJs, Js.Str(k)), v.toJs) }
+            case src => copyAllFields(src, tmp.fix) :: Nil
+          },
+          tmp.fix.toJs)
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: It won’t affect me accepting this PR, but just curious whether you prefer this or handling Splice/copyAllFields in `scope`. If it’s the latter, I can make the change when I submit my PR that exposes scope in $simpleMap.

File: core/src/main/scala/slamdata/engine/physical/mongodb/exprop.scala [hunk 2]
```diff
@@ -148,6 +148,8 @@ object ExprOp {
       case Multiply(l, r)        => binop(JsCore.Mult, l, r)
       case Neq(l, r)             => binop(JsCore.Neq, l, r)
       case Not(a)                => unop(JsCore.Not, a)
+
+      case Concat(l, r, Nil)     => binop(JsCore.Add, l, r)
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/exprop.scala]: Heh, should we rename `JsCore.Add` to `JsCore.MonoidOp`? 😉

File: core/src/main/scala/slamdata/engine/javascript/jscore.scala (hunk 1 above)
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: Yes, I think you mentioned that idea after I had already implemented it this way.

The advantage of having a primitive in JsCore is simpler/more efficient JS for the parts where we do know the shape, which is worth something I think. Still, It would be cleaner to move the loop to a function in scope, but how would that work? Does `toJs` return both a `Js.Expr` and map of definitions for the scope?

File: core/src/test/scala/slamdata/engine/javascript/jscore.scala [hunk 3]
```diff
@@ -112,6 +112,22 @@ class JsCoreSpecs extends Specification with TreeMatchers {
...
+      val expr = Splice(List(Obj(ListMap("foo" -> Select(Ident("bar").fix, "baz").fix)).fix)).fix
+      expr.toJs.render(0) must_==
+        "(function (__rez) { __rez.foo = (bar != null) ? bar.baz : undefined; return __rez })(\n  {  })"
+    }
+
+    "splice other expression" in {
+      val expr = Splice(List(Ident("foo").fix)).fix
+      expr.toJs.render(0) must_==
+        """(function (__rez) {
+          |  for (var __attr in (foo)) if (foo.hasOwnProperty(__attr)) __rez[__attr] = foo[__attr];
```
Comment (mossprescott) [inline core/src/test/scala/slamdata/engine/javascript/jscore.scala]: @sellout: this line could become `copyAll(foo, __rez)`, but I don't think it's that much clearer, since this line is already simple, by comparison with a lot of the JS we generate.

File: core/src/main/scala/slamdata/engine/javascript/jscore.scala (hunk 1 above)
Comment (sellout) [inline core/src/main/scala/slamdata/engine/javascript/jscore.scala]: I think I’ll wait on changing this, then – once you have a chance to review the `scope` stuff, we can come back to it.

The scope is attached to the WorkflowOp (and subsequent MapReduceTask), so `toJs` never sees it. Basically, the JsCore just refers to some unbound function, and `mapReduce()` makes sure the function is bound when it’s executed.

It’ll hopefully make more sense once you see it.

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala [hunk 4]
```diff
@@ -1177,88 +1153,62 @@ object Workflow {
...
+      flatten match {
+        case x :: Nil => body(List(Ident("elem").fix -> x))
+        case _        => body(flatten.zipWithIndex.map { case (x, i) => Ident("elem" + i).fix -> x })
+      }
     }
 
-    def kleisliCompose(f0: $SimpleFlatMap[A]) =
-      $SimpleFlatMap(
+    def kleisliCompose(f0: $SimpleMap[A]) =
+      $SimpleMap(
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala]: Maybe we should just rename this to `compose`? I mostly added the prefixes just to distinguish the myriad cases, but now that we’ve reduced 4 cases to 1, I’m not sure it’s worth it.

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala [hunk 5]
```diff
@@ -208,10 +202,9 @@ object Workflow {
             $flatMap($FlatMap.kleisliCompose(fn, fn0), _)(src0))
         case _                   => op
       }
-      case fm @ $SimpleFlatMap(src, _, _) => src.unFix match {
-        case sm @ $SimpleMap(_, _)         => Term(fm.mapCompose(sm))
-        case fm0 @ $SimpleFlatMap(_, _, _) => Term(fm.kleisliCompose(fm0))
-        case _                             => op
+      case fm @ $SimpleMap(src, _, _) => src.unFix match {
+        case fm0 @ $SimpleMap(_, _, _) => Term(fm.kleisliCompose(fm0))
```
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala]: Rename `fm*` -> `sm*`? Also, see other comment about `kleisliCompose`.

**Comment by sellout** [comment]
This looks _great_ to me. I was initially concerned about how much new code there was, but it looks like the changes are net negative, and all the extra code is in tests, so that’s fantastic.

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala [hunk 6]
```diff
@@ -1177,88 +1153,62 @@ object Workflow {
...
-          Js.Return(Js.Ident("rez"))))
+                  Js.VarDef(List("each" -> Js.Call(Js.Ident("clone"), List(Js.Ident("value")))))) ++
+                fs.map { case (n, x) =>
+                  safeAssign(x(Ident("each").fix), Access(x(Ident("value").fix), n).fix) } ++
+                List(Call(Select(Ident("rez").fix, "push").fix,
+                  List(
+                    Arr(List(
+                      Call(Ident("ObjectId").fix, Nil).fix,
+                       expr(Ident("each").fix))).fix)).fix.toJs))) { case (inner, (n, m)) =>
+                         Js.ForIn(n.toJs.asInstanceOf[Js.Ident], m(Ident("value").fix).toJs, inner)
```
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala]: @sellout: I meant to point this little bit of ugliness out. I don't like using `asInstanceOf` one bit--I happen to know that `n` is JsCore.Ident, and that its toJs will be Js.Ident, but that information gets lost a couple of different ways.

Obviously, I could just use `String`. Any better ideas?

We tend to repeat the names of our temporaries in the code quite a bit, partially because of this sort of thing. Wish I had a better solution.

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala (hunk 4 above)
Comment (mossprescott) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala]: Yes, absolutely. Actually I was tempted to rename it to `<<<`, or switch to `>>>`, since that's what JsMacro provides. Preference?

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala (hunk 6 above)
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala]: No, not really – I’ve used this in the past as well (although I think I eventually managed to eliminate those cases). Hand-waving: “type families”, “mutualrec” … maybe some day we’ll get back to that.

File: core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala (hunk 4 above)
Comment (sellout) [inline core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala]: Yeah, I like these – I want both. Is it worth making a small trait that defines them in terms of each other, and then we just override one here and in JsMacro?

**Comment by mossprescott** [comment]
I made those small changes, but did not introduce a trait for `<<<`/`>>>`, and I also found a simple way to get rid of the cast.

**Comment by sellout** [comment]
Ah, yeah, good fix for the cast.
